apiVersion: v1
kind: Service
metadata:
  name: ql3-approval-management
  namespace: qinglong3-system
  labels:
    app.kubernetes.io/name: ql3-approval-management
    app.kubernetes.io/component: approval-management
    app.kubernetes.io/part-of: qinglong3
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ql3-approval-management
    app.kubernetes.io/component: approval-management
  ports:
    - name: https
      port: 8447
      targetPort: https
      protocol: TCP
