apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ql3-automation-management
  namespace: qinglong3-system
spec:
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: ql3-postgres
      ports:
        - protocol: TCP
          port: 5432
