apiVersion: v1
kind: ServiceAccount
metadata:
  name: ql3-provider-credential-management-client
  namespace: qinglong3-system
  labels:
    app.kubernetes.io/name: ql3-provider-credential-management-client
    app.kubernetes.io/component: provider-credential-management-client
    app.kubernetes.io/part-of: qinglong3
automountServiceAccountToken: false
