apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qinglong3-system

resources:
  - namespace.yaml
  - service-account.yaml
  - service.yaml
  - deployment.yaml
  - pod-disruption-budget.yaml
