apiVersion: v1
kind: ServiceAccount
metadata:
  name: ql3-cluster-control
  labels:
    app.kubernetes.io/name: ql3-cluster-control
    app.kubernetes.io/component: control-plane
automountServiceAccountToken: false
