export interface PostgresSchemaContractTable {
  readonly name: string;
  readonly columns: readonly string[];
}

export interface PostgresSchemaContractFunction {
  readonly name: string;
  readonly identityArguments: string;
  readonly owner: 'ql3_migration';
  readonly securityDefiner: boolean;
  readonly volatility: 'volatile';
  readonly configuration: readonly string[];
}

export interface PostgresSchemaContractTrigger {
  readonly name: string;
  readonly tableName: string;
  readonly functionName: string;
}

export interface PostgresSchemaContract {
  readonly schema: 'ql3';
  readonly contractName: 'control-core';
  readonly contractVersion: 64;
  readonly migrationId: 'pg-0065-approved-action-manual-recovery';
  readonly minimumServerMajor: 16;
  readonly maximumServerMajor: 18;
  readonly capabilities: Readonly<{
    run_core: 1;
    run_attempt_log_retention: 1;
    run_management_boundary: 1;
    run_management_stop: 1;
    run_dispatch_lease: 1;
    run_retry_policy: 1;
    project_policy: 1;
    api_credential: 1;
    api_credential_admin: 1;
    api_credential_pepper_binding: 1;
    approved_action: 1;
    approved_action_execution: 1;
    approved_action_manual_recovery: 1;
    approval_management_boundary: 1;
    automation_management_boundary: 1;
    automation_management_identity_keyset_ledger: 1;
    cluster_recovery: 1;
    cluster_recovery_claim: 1;
    cluster_scheduler_admission: 1;
    database_role_grants: 1;
    cluster_execution_revision: 1;
    identity_admin: 1;
    plugin_package_admission: 1;
    plugin_package_authority_split: 1;
    plugin_package_automation_publication: 1;
    plugin_package_automation_security_withdrawal: 1;
    plugin_package_automation_start_guard: 1;
    plugin_package_workflow_admission: 1;
    plugin_package_workflow_run_list: 1;
    plugin_package_workflow_task_attempt_admission: 1;
    plugin_package_identity_keyset_ledger: 1;
    plugin_package_install: 1;
    plugin_package_lifecycle: 1;
    plugin_package_lifecycle_plan: 1;
    plugin_package_management_quota: 1;
    plugin_package_materialized_revision: 1;
    plugin_package_secret_binding: 1;
    plugin_package_secret_binding_approval_plan: 1;
    plugin_package_secret_binding_transition: 1;
    plugin_package_secret_binding_transition_approval_plan: 1;
    plugin_package_secret_binding_transition_receipt: 1;
    plugin_package_secret_materialization: 1;
    plugin_package_proposal: 1;
    plugin_package_publisher_provenance: 1;
    plugin_package_publisher_trust_authority: 1;
    plugin_package_publisher_trust_transition: 1;
    plugin_package_quarantine: 1;
    plugin_package_task_reconciliation: 1;
    project_tool_definition_snapshot: 1;
    security_audit: 1;
    security_audit_query: 1;
    step_run: 1;
    task_definition: 1;
    tool_execution_evidence: 1;
    tool_execution_artifact_binding: 1;
    tool_execution_completion: 1;
    tool_execution_failure_completion: 1;
    tool_result_key_catalog: 1;
    tool_result_rekey: 1;
    tool_execution_start_barrier: 1;
    tool_invocation_artifact: 1;
    trigger_definition: 1;
    worker_session: 1;
    worker_credential: 1;
    worker_credential_delivery: 1;
    worker_credential_execution_receipt: 1;
    worker_credential_management_identity_keyset_ledger: 1;
    worker_credential_management_plan: 1;
    worker_credential_management_quota: 1;
    worker_credential_preapproved_activation: 1;
    worker_credential_stage_discard: 1;
    worker_attestation: 1;
  }>;
  readonly tables: readonly PostgresSchemaContractTable[];
  readonly indexes: readonly string[];
  readonly checks: readonly string[];
  readonly foreignKeys: readonly string[];
  readonly functions: readonly PostgresSchemaContractFunction[];
  readonly triggers: readonly PostgresSchemaContractTrigger[];
}

function table(
  name: string,
  columns: readonly string[],
): PostgresSchemaContractTable {
  return Object.freeze({ name, columns: Object.freeze([...columns]) });
}

export const postgresqlControlSchemaContract: PostgresSchemaContract =
  Object.freeze({
    schema: 'ql3',
    contractName: 'control-core',
    contractVersion: 64,
    migrationId: 'pg-0065-approved-action-manual-recovery',
    minimumServerMajor: 16,
    maximumServerMajor: 18,
    capabilities: Object.freeze({
      api_credential: 1,
      api_credential_admin: 1,
      api_credential_pepper_binding: 1,
      approved_action: 1,
      approved_action_execution: 1,
      approved_action_manual_recovery: 1,
      approval_management_boundary: 1,
      automation_management_boundary: 1,
      automation_management_identity_keyset_ledger: 1,
      cluster_execution_revision: 1,
      cluster_recovery: 1,
      cluster_recovery_claim: 1,
      cluster_scheduler_admission: 1,
      database_role_grants: 1,
      identity_admin: 1,
      plugin_package_admission: 1,
      plugin_package_authority_split: 1,
      plugin_package_automation_publication: 1,
      plugin_package_automation_security_withdrawal: 1,
      plugin_package_automation_start_guard: 1,
      plugin_package_workflow_admission: 1,
      plugin_package_workflow_run_list: 1,
      plugin_package_workflow_task_attempt_admission: 1,
      plugin_package_identity_keyset_ledger: 1,
      plugin_package_install: 1,
      plugin_package_lifecycle: 1,
      plugin_package_lifecycle_plan: 1,
      plugin_package_management_quota: 1,
      plugin_package_materialized_revision: 1,
      plugin_package_secret_binding: 1,
      plugin_package_secret_binding_approval_plan: 1,
      plugin_package_secret_binding_transition: 1,
      plugin_package_secret_binding_transition_approval_plan: 1,
      plugin_package_secret_binding_transition_receipt: 1,
      plugin_package_secret_materialization: 1,
      plugin_package_proposal: 1,
      plugin_package_publisher_provenance: 1,
      plugin_package_publisher_trust_authority: 1,
      plugin_package_publisher_trust_transition: 1,
      plugin_package_quarantine: 1,
      plugin_package_task_reconciliation: 1,
      project_policy: 1,
      project_tool_definition_snapshot: 1,
      run_core: 1,
      run_attempt_log_retention: 1,
      run_management_boundary: 1,
      run_management_stop: 1,
      run_dispatch_lease: 1,
      run_retry_policy: 1,
      security_audit: 1,
      security_audit_query: 1,
      step_run: 1,
      task_definition: 1,
      tool_execution_evidence: 1,
      tool_execution_artifact_binding: 1,
      tool_execution_completion: 1,
      tool_execution_failure_completion: 1,
      tool_result_key_catalog: 1,
      tool_result_rekey: 1,
      tool_execution_start_barrier: 1,
      tool_invocation_artifact: 1,
      trigger_definition: 1,
      worker_session: 1,
      worker_credential: 1,
      worker_credential_delivery: 1,
      worker_credential_execution_receipt: 1,
      worker_credential_management_identity_keyset_ledger: 1,
      worker_credential_management_plan: 1,
      worker_credential_management_quota: 1,
      worker_credential_preapproved_activation: 1,
      worker_credential_stage_discard: 1,
      worker_attestation: 1,
    }),
    tables: Object.freeze([
      table('schema_migrations', [
        'migration_id',
        'stream_id',
        'dialect',
        'checksum',
        'applied_at_ms',
      ]),
      table('schema_capabilities', [
        'contract_name',
        'contract_version',
        'migration_id',
        'capabilities',
        'updated_at_ms',
      ]),
      table('projects', [
        'id',
        'name',
        'slug',
        'status',
        'version',
        'created_at_ms',
        'updated_at_ms',
      ]),
      table('plugin_package_installs', [
        'installation_id',
        'project_id',
        'package_name',
        'package_version',
        'operation',
        'lock_digest',
        'target_generation',
        'previous_active_lock_digest',
        'active_lock_digest',
        'state',
        'version',
        'last_mutation_id',
        'last_mutation_digest',
        'lock_json',
        'record_json',
        'record_digest',
        'created_at_ms',
        'updated_at_ms',
      ]),
      table('plugin_package_install_heads', [
        'project_id',
        'package_name',
        'installation_id',
      ]),
      table('plugin_package_install_mutations', [
        'installation_id',
        'mutation_id',
        'mutation_digest',
        'resulting_record_digest',
        'occurred_at_ms',
      ]),
      table('plugin_package_materialized_revisions', [
        'generation_digest',
        'project_id',
        'package_name',
        'generation',
        'lock_digest',
        'manifest_digest',
        'revision_digest',
        'revision_json',
        'created_at_ms',
      ]),
      table('plugin_package_secret_bindings', [
        'generation_digest',
        'project_id',
        'package_name',
        'installation_id',
        'lock_digest',
        'generation',
        'manifest_digest',
        'authority_kind',
        'evidence_digest',
        'bound_at_ms',
        'binding_digest',
        'binding_json',
      ]),
      table('plugin_package_secret_binding_approval_plans', [
        'action_ref',
        'approval_plan_digest',
        'binding_plan_digest',
        'generation_digest',
        'project_id',
        'package_name',
        'installation_id',
        'lock_digest',
        'generation',
        'manifest_digest',
        'requested_by_type',
        'requested_by_id',
        'planned_at_ms',
        'expires_at_ms',
        'plan_json',
      ]),
      table('plugin_package_secret_binding_transition_approval_plans', [
        'action_ref',
        'approval_plan_digest',
        'transition_digest',
        'generation_digest',
        'project_id',
        'package_name',
        'installation_id',
        'lock_digest',
        'generation',
        'manifest_digest',
        'previous_active_lock_digest',
        'requested_by_type',
        'requested_by_id',
        'planned_at_ms',
        'expires_at_ms',
        'plan_json',
      ]),
      table('plugin_package_secret_binding_transition_receipts', [
        'generation_digest',
        'transition_digest',
        'project_id',
        'package_name',
        'installation_id',
        'lock_digest',
        'generation',
        'manifest_digest',
        'previous_active_lock_digest',
        'authority_kind',
        'evidence_digest',
        'binding_digest',
        'committed_at_ms',
        'receipt_digest',
        'receipt_json',
      ]),
      table('project_tool_definition_snapshots', [
        'project_id',
        'active_vector_digest',
        'definitions_digest',
        'snapshot_digest',
        'snapshot_json',
        'committed_at_ms',
      ]),
      table('project_tool_definition_snapshot_sources', [
        'project_id',
        'active_vector_digest',
        'package_name',
        'installation_id',
        'generation',
        'generation_digest',
        'lock_digest',
        'revision_digest',
      ]),
      table('plugin_package_quarantine_events', [
        'event_digest',
        'mutation_id',
        'revocation_receipt_digest',
        'impact_digest',
        'project_id',
        'package_name',
        'installation_id',
        'lock_digest',
        'install_state',
        'install_version',
        'install_record_digest',
        'active_lock_digest',
        'proposer_type',
        'proposer_id',
        'confirmer_type',
        'confirmer_id',
        'authorization_mode',
        'reason_code',
        'occurred_at_ms',
        'event_json',
      ]),
      table('plugin_package_withdrawal_receipts', [
        'event_digest',
        'receipt_digest',
        'project_id',
        'capability_status',
        'task_count',
        'previous_active_vector_digest',
        'current_active_vector_digest',
        'current_tool_snapshot_digest',
        'retained_source_count',
        'committed_at_ms',
        'receipt_json',
      ]),
      table('plugin_package_withdrawal_tasks', [
        'event_digest',
        'project_id',
        'task_id',
        'previous_revision',
        'disabled_revision',
        'previous_content_digest',
        'disabled_content_digest',
      ]),
      table('plugin_package_lifecycle_events', [
        'event_digest',
        'mutation_id',
        'dispatch_id',
        'approved_action_type',
        'action',
        'project_id',
        'package_name',
        'installation_id',
        'lock_digest',
        'install_version',
        'install_record_digest',
        'expected_version',
        'expected_disposition',
        'expected_event_digest',
        'generation_digest',
        'materialized_revision_digest',
        'current_tool_snapshot_digest',
        'reference_graph_digest',
        'impact_digest',
        'action_digest',
        'requested_by_type',
        'requested_by_id',
        'approved_by_type',
        'approved_by_id',
        'authorization_mode',
        'occurred_at_ms',
        'event_json',
      ]),
      table('plugin_package_lifecycle_heads', [
        'project_id',
        'package_name',
        'installation_id',
        'lock_digest',
        'install_record_digest',
        'version',
        'disposition',
        'event_digest',
        'updated_at_ms',
      ]),
      table('plugin_package_lifecycle_receipts', [
        'event_digest',
        'receipt_digest',
        'project_id',
        'action',
        'capability_status',
        'task_count',
        'previous_active_vector_digest',
        'current_active_vector_digest',
        'current_tool_snapshot_digest',
        'retained_source_count',
        'committed_at_ms',
        'receipt_json',
      ]),
      table('plugin_package_lifecycle_tasks', [
        'event_digest',
        'project_id',
        'task_id',
        'previous_revision',
        'current_revision',
        'previous_content_digest',
        'current_content_digest',
        'previous_enabled',
        'current_enabled',
      ]),
      table('plugin_package_lifecycle_plans', [
        'action_ref',
        'plan_digest',
        'action',
        'project_id',
        'package_name',
        'installation_id',
        'lock_digest',
        'impact_digest',
        'requested_by_type',
        'requested_by_id',
        'planned_at_ms',
        'expires_at_ms',
        'plan_json',
      ]),
      table('plugin_package_automation_disposition_events', [
        'event_digest',
        'event_kind',
      ]),
      table('plugin_package_automation_publications', [
        'publication_digest',
        'project_id',
        'package_name',
        'installation_id',
        'lock_digest',
        'generation',
        'generation_digest',
        'materialized_revision_digest',
        'state',
        'version',
        'previous_publication_digest',
        'lifecycle_event_digest',
        'published_at_ms',
        'publication_json',
      ]),
      table('plugin_package_automation_publication_heads', [
        'project_id',
        'package_name',
        'publication_digest',
        'generation_digest',
        'state',
        'version',
        'updated_at_ms',
      ]),
      table('plugin_package_workflow_admissions', [
        'plan_digest',
        'plan_id',
        'run_id',
        'project_id',
        'package_name',
        'installation_id',
        'lock_digest',
        'generation',
        'generation_digest',
        'materialized_revision_digest',
        'publication_digest',
        'workflow_id',
        'workflow_definition_digest',
        'step_count',
        'admitted_at_ms',
        'final_run_version',
        'final_run_event_sequence',
        'receipt_digest',
        'plan_json',
        'receipt_json',
      ]),
      table('plugin_package_workflow_admission_steps', [
        'plan_digest',
        'run_id',
        'step_key',
        'step_run_id',
        'task_id',
        'task_definition_ref',
        'task_definition_digest',
        'needs_json',
        'initial_status',
        'mutation_id',
        'event_id',
      ]),
      table('plugin_package_workflow_task_attempt_admissions', [
        'receipt_digest',
        'attempt_id',
        'plan_digest',
        'run_id',
        'step_run_id',
        'step_run_version',
        'step_run_digest',
        'generation_digest',
        'resource_task_id',
        'task_reconciliation_receipt_digest',
        'project_id',
        'task_id',
        'source_revision',
        'task_revision',
        'task_definition_digest',
        'executor_type',
        'execution_digest',
        'attempt_number',
        'event_id',
        'run_version',
        'run_event_sequence',
        'admitted_at_ms',
        'receipt_json',
      ]),
      table('plugin_package_publisher_provenance', [
        'installation_id',
        'project_id',
        'package_name',
        'lock_digest',
        'artifact_digest',
        'manifest_digest',
        'content_digest',
        'stage_evidence_digest',
        'publisher',
        'key_id',
        'signature_digest',
        'key_not_before_ms',
        'key_not_after_ms',
        'verified_at_ms',
        'provenance_digest',
        'provenance_json',
      ]),
      table('plugin_package_publisher_revocation_receipts', [
        'receipt_digest',
        'mutation_id',
        'publisher',
        'key_id',
        'previous_trust_digest',
        'current_trust_digest',
        'proposer_type',
        'proposer_id',
        'confirmer_type',
        'confirmer_id',
        'authorization_mode',
        'reason_code',
        'revoked_at_ms',
        'receipt_json',
      ]),
      table('plugin_package_publisher_revocation_impacts', [
        'revocation_receipt_digest',
        'impact_digest',
        'item_count',
        'generated_at_ms',
        'impact_json',
      ]),
      table('plugin_package_publisher_revocation_impact_items', [
        'impact_digest',
        'provenance_digest',
        'project_id',
        'package_name',
        'installation_id',
        'lock_digest',
      ]),
      table('plugin_package_publisher_trust_snapshots', [
        'snapshot_digest',
        'key_count',
        'observed_by',
        'observed_at_ms',
        'snapshot_json',
      ]),
      table('plugin_package_publisher_trust_heads', [
        'authority_id',
        'generation',
        'base_snapshot_digest',
        'effective_trust_digest',
        'updated_at_ms',
        'head_digest',
        'head_json',
      ]),
      table('plugin_package_publisher_revocation_proposals', [
        'action_ref',
        'project_id',
        'authority_id',
        'trust_generation',
        'publisher',
        'key_id',
        'previous_trust_digest',
        'current_trust_digest',
        'action_type',
        'permission',
        'action_digest',
        'preview_digest',
        'authorization_mode',
        'reason_code',
        'proposed_by_type',
        'proposed_by_id',
        'proposer_assurance',
        'fence_project_version',
        'fence_binding_version',
        'created_at_ms',
        'proposal_json',
        'proposal_digest',
      ]),
      table('plugin_package_publisher_trust_transition_proposals', [
        'action_ref',
        'project_id',
        'authority_id',
        'trust_generation',
        'mode',
        'publisher',
        'key_id',
        'previous_trust_digest',
        'current_trust_digest',
        'action_type',
        'permission',
        'action_digest',
        'preview_digest',
        'proposed_by_type',
        'proposed_by_id',
        'proposer_assurance',
        'fence_project_version',
        'fence_binding_version',
        'created_at_ms',
        'proposal_json',
        'proposal_digest',
      ]),
      table('plugin_package_publisher_trust_transition_receipts', [
        'mutation_id',
        'proposal_digest',
        'authority_id',
        'previous_generation',
        'current_generation',
        'mode',
        'publisher',
        'key_id',
        'previous_trust_digest',
        'current_trust_digest',
        'proposer_type',
        'proposer_id',
        'confirmer_type',
        'confirmer_id',
        'retirement_matching_installations',
        'executed_at_ms',
        'receipt_json',
        'receipt_digest',
      ]),
      table('plugin_package_task_ownerships', [
        'project_id',
        'task_id',
        'package_name',
        'claimed_generation_digest',
        'created_at_ms',
      ]),
      table('plugin_package_task_reconciliations', [
        'generation_digest',
        'project_id',
        'package_name',
        'generation',
        'materialized_revision_digest',
        'lock_digest',
        'previous_lock_digest',
        'receipt_digest',
        'receipt_json',
        'committed_at_ms',
      ]),
      table('plugin_package_task_reconciliation_items', [
        'generation_digest',
        'task_id',
        'revision',
        'disposition',
        'content_digest',
      ]),
      table('approval_requests', [
        'request_id',
        'project_id',
        'version',
        'state',
        'action_type',
        'action_ref',
        'action_digest',
        'preview_digest',
        'requested_by_type',
        'requested_by_id',
        'decision_id',
        'consumption_id',
        'dispatch_id',
        'expires_at_ms',
        'request_json',
        'request_digest',
        'updated_at_ms',
      ]),
      table('approved_action_dispatches', [
        'dispatch_id',
        'approval_request_id',
        'project_id',
        'action_type',
        'action_ref',
        'action_digest',
        'preview_digest',
        'dispatch_json',
        'dispatch_digest',
        'created_at_ms',
      ]),
      table('approved_action_executions', [
        'dispatch_id',
        'dispatch_digest',
        'project_id',
        'status',
        'version',
        'attempt_count',
        'max_attempts',
        'eligible_at_ms',
        'next_attempt_at_ms',
        'lease_owner',
        'lease_token',
        'lease_expires_at_ms',
        'started_at_ms',
        'result_mutation_id',
        'result_code',
        'result_digest',
        'completed_at_ms',
        'created_at_ms',
        'updated_at_ms',
        'execution_json',
        'execution_digest',
      ]),
      table('approved_action_manual_recovery_resolutions', [
        'dispatch_id',
        'dispatch_digest',
        'project_id',
        'action_type',
        'action_digest',
        'execution_version',
        'execution_digest',
        'mutation_id',
        'decision',
        'evidence_digest',
        'reason_code',
        'resolved_by_type',
        'resolved_by_id',
        'authentication_id',
        'assurance',
        'authenticated_at_ms',
        'project_version',
        'binding_version',
        'audit_event_id',
        'resolved_at_ms',
        'resolution_json',
        'resolution_digest',
      ]),
      table('plugin_package_install_proposals', [
        'action_ref',
        'project_id',
        'action_type',
        'permission',
        'action_digest',
        'preview_digest',
        'proposed_by_type',
        'proposed_by_id',
        'fence_project_version',
        'fence_binding_version',
        'created_at_ms',
        'proposal_json',
        'proposal_digest',
      ]),
      table('plugin_package_management_quota_buckets', [
        'project_id',
        'subject_type',
        'subject_id',
        'operation',
        'window_started_at_ms',
        'consumed_count',
        'receipt_ids',
        'updated_at_ms',
      ]),
      table('worker_credential_management_quota_buckets', [
        'project_id',
        'subject_type',
        'subject_id',
        'operation',
        'window_started_at_ms',
        'consumed_count',
        'receipt_ids',
        'updated_at_ms',
      ]),
      table('plugin_package_identity_keyset_ledger', [
        'authority',
        'generation',
        'digest',
        'issuer',
        'audience',
        'active_key_ids',
        'revoked_key_ids',
        'updated_at_ms',
      ]),
      table('plugin_package_admission_receipts', [
        'dispatch_id',
        'dispatch_digest',
        'approval_request_id',
        'action_ref',
        'project_id',
        'package_name',
        'installation_id',
        'lock_digest',
        'record_digest',
        'mutation_id',
        'mutation_digest',
        'audit_event_id',
        'admitted_at_ms',
        'receipt_json',
        'receipt_digest',
      ]),
      table('task_definitions', [
        'project_id',
        'task_id',
        'current_revision',
        'created_at_ms',
        'updated_at_ms',
      ]),
      table('task_definition_revisions', [
        'project_id',
        'task_id',
        'revision',
        'mutation_id',
        'name',
        'description',
        'kind',
        'spec_json',
        'labels_json',
        'enabled',
        'content_digest',
        'created_at_ms',
      ]),
      table('task_execution_revisions', [
        'project_id',
        'task_id',
        'source_revision',
        'task_revision',
        'source_content_digest',
        'executor_type',
        'plan_schema',
        'plan_json',
        'content_digest',
        'created_at_ms',
      ]),
      table('triggers', [
        'project_id',
        'trigger_id',
        'task_id',
        'current_revision',
        'created_at_ms',
        'updated_at_ms',
      ]),
      table('trigger_revisions', [
        'project_id',
        'trigger_id',
        'revision',
        'mutation_id',
        'task_id',
        'task_revision',
        'task_content_digest',
        'spec_json',
        'enabled',
        'content_digest',
        'created_at_ms',
      ]),
      table('trigger_schedules', [
        'project_id',
        'trigger_id',
        'trigger_revision',
        'next_fire_at_ms',
        'last_scheduled_at_ms',
        'state_version',
        'claim_owner',
        'claim_token',
        'claim_version',
        'claim_expires_at_ms',
        'updated_at_ms',
      ]),
      table('project_role_bindings', [
        'project_id',
        'subject_type',
        'subject_id',
        'version',
        'state',
        'role',
        'mutation_id',
        'changed_by_type',
        'changed_by_id',
        'created_at_ms',
      ]),
      table('identity_subjects', [
        'subject_type',
        'subject_id',
        'status',
        'version',
        'created_at_ms',
        'updated_at_ms',
      ]),
      table('api_credentials', [
        'credential_id',
        'version',
        'state',
        'subject_type',
        'subject_id',
        'pepper_key_id',
        'secret_digest',
        'created_at_ms',
        'not_before_at_ms',
        'expires_at_ms',
      ]),
      table('security_audit_events', [
        'event_id',
        'request_id',
        'operation_id',
        'project_id',
        'subject_type',
        'subject_id',
        'authentication_id',
        'outcome',
        'reasons',
        'project_version',
        'binding_version',
        'occurred_at_ms',
      ]),
      table('identity_subject_mutations', [
        'mutation_id',
        'operation',
        'subject_type',
        'subject_id',
        'subject_version',
        'expected_previous_version',
        'status',
        'changed_by_type',
        'changed_by_id',
        'audit_event_id',
        'identity_created_at_ms',
        'created_at_ms',
      ]),
      table('api_credential_mutations', [
        'mutation_id',
        'operation',
        'credential_id',
        'credential_version',
        'expected_previous_version',
        'state',
        'subject_type',
        'subject_id',
        'subject_status',
        'changed_by_type',
        'changed_by_id',
        'audit_event_id',
        'created_at_ms',
      ]),
      table('runs', [
        'id',
        'project_id',
        'task_id',
        'task_revision',
        'task_name',
        'task_snapshot_ref',
        'legacy_cron_id',
        'parent_run_id',
        'retry_of_run_id',
        'trigger_id',
        'trigger_type',
        'execution_origin',
        'execution_owner',
        'triggered_by',
        'request_id',
        'scheduled_for_ms',
        'status',
        'version',
        'event_sequence',
        'priority',
        'idempotency_key',
        'input_ref',
        'output_ref',
        'created_at_ms',
        'queued_at_ms',
        'started_at_ms',
        'finished_at_ms',
        'cancel_requested_at_ms',
        'cancel_reason',
        'error_code',
        'error_summary',
      ]),
      table('step_runs', [
        'id',
        'run_id',
        'parent_step_run_id',
        'step_key',
        'kind',
        'definition_ref',
        'definition_digest',
        'required',
        'status',
        'version',
        'attempt_count',
        'input_ref',
        'output_ref',
        'approval_request_id',
        'ready_at_ms',
        'started_at_ms',
        'finished_at_ms',
        'result_code',
        'error_summary',
        'created_at_ms',
        'updated_at_ms',
        'last_mutation_id',
        'step_run_digest',
        'step_run_json',
      ]),
      table('tool_execution_trace_anchors', [
        'trace_id',
        'span_id',
        'parent_span_id',
        'project_id',
        'run_id',
        'step_run_id',
        'invocation_plan_digest',
        'binding_digest',
        'adapter_digest',
        'redaction_contract_digest',
        'audit_contract_digest',
        'created_at_ms',
        'trace_digest',
        'trace_json',
      ]),
      table('tool_execution_audit_receipts', [
        'event_id',
        'project_id',
        'run_id',
        'step_run_id',
        'trace_id',
        'span_id',
        'trace_digest',
        'invocation_plan_digest',
        'binding_digest',
        'audit_record_digest',
        'created_at_ms',
        'receipt_digest',
        'audit_json',
        'receipt_json',
      ]),
      table('tool_execution_start_barriers', [
        'start_id',
        'project_id',
        'run_id',
        'step_run_id',
        'started_step_run_version',
        'step_run_mutation_id',
        'run_event_id',
        'trace_id',
        'span_id',
        'audit_event_id',
        'command_digest',
        'barrier_digest',
        'started_at_ms',
        'barrier_json',
      ]),
      table('tool_invocation_input_artifacts', [
        'artifact_id',
        'project_id',
        'action_ref',
        'input_digest',
        'invocation_action_digest',
        'artifact_digest',
        'key_id',
        'algorithm',
        'plaintext_bytes',
        'sealed_at_ms',
        'artifact_json',
      ]),
      table('tool_invocation_preview_artifacts', [
        'artifact_id',
        'project_id',
        'action_ref',
        'action_digest',
        'preview_digest',
        'redaction_contract_digest',
        'artifact_digest',
        'byte_length',
        'sealed_at_ms',
        'artifact_json',
      ]),
      table('tool_execution_start_artifact_bindings', [
        'start_id',
        'project_id',
        'action_ref',
        'input_artifact_id',
        'input_artifact_digest',
        'input_digest',
        'preview_artifact_id',
        'preview_artifact_digest',
        'action_digest',
        'preview_digest',
        'redaction_contract_digest',
        'bound_at_ms',
      ]),
      table('tool_execution_completions', [
        'start_id',
        'artifact_id',
        'project_id',
        'run_id',
        'step_run_id',
        'started_step_run_version',
        'completed_step_run_version',
        'barrier_digest',
        'adapter_digest',
        'output_digest',
        'execution_result_digest',
        'artifact_digest',
        'key_id',
        'algorithm',
        'plaintext_bytes',
        'step_run_mutation_id',
        'step_run_mutation_digest',
        'completed_step_run_digest',
        'run_event_id',
        'completed_at_ms',
        'completion_digest',
        'artifact_json',
        'completion_json',
      ]),
      table('tool_execution_failure_completions', [
        'start_id',
        'project_id',
        'run_id',
        'step_run_id',
        'started_step_run_version',
        'completed_step_run_version',
        'barrier_digest',
        'adapter_digest',
        'outcome',
        'result_code',
        'error_summary',
        'step_run_mutation_id',
        'step_run_mutation_digest',
        'completed_step_run_digest',
        'run_event_id',
        'completed_at_ms',
        'completion_digest',
        'completion_json',
      ]),
      table('tool_result_key_catalog_generations', [
        'authority',
        'generation',
        'previous_generation',
        'previous_catalog_digest',
        'active_key_id',
        'mutation_kind',
        'mutation_id',
        'catalog_digest',
        'command_digest',
        'committed_at_ms',
        'catalog_json',
      ]),
      table('tool_execution_result_key_bindings', [
        'start_id',
        'artifact_id',
        'artifact_digest',
        'catalog_authority',
        'catalog_generation',
        'catalog_digest',
        'key_id',
        'material_proof',
        'binding_digest',
      ]),
      table('tool_execution_result_rekey_overlays', [
        'overlay_id',
        'artifact_id',
        'source_binding_digest',
        'revision',
        'previous_overlay_digest',
        'from_key_id',
        'target_catalog_authority',
        'target_catalog_generation',
        'target_catalog_digest',
        'target_key_id',
        'target_material_proof',
        'mutation_id',
        'command_digest',
        'overlay_digest',
        'rekeyed_at_ms',
        'overlay_json',
      ]),
      table('tool_execution_result_rekey_heads', [
        'artifact_id',
        'revision',
        'overlay_id',
        'overlay_digest',
        'target_catalog_generation',
        'target_catalog_digest',
        'target_key_id',
        'updated_at_ms',
      ]),
      table('tool_result_key_retirement_receipts', [
        'receipt_digest',
        'catalog_authority',
        'catalog_generation',
        'catalog_digest',
        'key_id',
        'material_proof',
        'mutation_id',
        'command_digest',
        'binding_count',
        'overlay_head_count',
        'uncovered_binding_count',
        'uncovered_overlay_head_count',
        'coverage_digest',
        'created_at_ms',
        'receipt_json',
      ]),
      table('run_attempts', [
        'id',
        'run_id',
        'step_run_id',
        'attempt',
        'status',
        'executor_type',
        'worker_id',
        'worker_session_id',
        'worker_generation',
        'executor_handle',
        'pid',
        'log_artifact_id',
        'lease_token',
        'lease_token_digest',
        'lease_generation',
        'lease_version',
        'lease_expires_at_ms',
        'offer_id',
        'deadline_at_ms',
        'callback_token_hash',
        'callback_sequence',
        'created_at_ms',
        'started_at_ms',
        'finished_at_ms',
        'exit_code',
        'error_code',
        'error_summary',
      ]),
      table('run_attempt_log_retention_controls', [
        'attempt_id',
        'project_id',
        'run_id',
        'log_artifact_id',
        'executor_type',
        'finished_at_ms',
        'eligible_at_ms',
        'state',
        'claim_owner',
        'claim_token',
        'claim_version',
        'claim_expires_at_ms',
        'next_claim_at_ms',
        'failure_count',
        'last_failure_code',
        'created_at_ms',
        'updated_at_ms',
      ]),
      table('run_attempt_log_artifact_tombstones', [
        'log_artifact_id',
        'project_id',
        'run_id',
        'attempt_id',
        'executor_type',
        'finished_at_ms',
        'eligible_at_ms',
        'retired_at_ms',
        'disposition',
        'byte_length',
        'truncated',
        'maximum_bytes',
        'truncation_observed_at_ms',
        'record_digest',
      ]),
      table('worker_sessions', [
        'worker_id',
        'session_id',
        'generation',
        'status',
        'version',
        'capabilities_json',
        'capabilities_hash',
        'max_concurrent_runs',
        'available_slots',
        'registered_at_ms',
        'last_heartbeat_at_ms',
        'lease_expires_at_ms',
        'updated_at_ms',
      ]),
      table('run_dispatch_leases', [
        'attempt_id',
        'run_id',
        'status',
        'version',
        'lease_generation',
        'worker_id',
        'worker_session_id',
        'worker_generation',
        'lease_token_digest',
        'offer_id',
        'acquired_at_ms',
        'renewed_at_ms',
        'expires_at_ms',
        'released_at_ms',
        'release_reason',
        'completed_at_ms',
        'updated_at_ms',
      ]),
      table('worker_credentials', [
        'credential_id',
        'version',
        'state',
        'worker_id',
        'secret_digest',
        'created_at_ms',
        'not_before_at_ms',
        'expires_at_ms',
      ]),
      table('worker_credential_management_plans', [
        'action_ref',
        'authority_project_id',
        'action',
        'delivery_id',
        'worker_id',
        'credential_id',
        'previous_credential_id',
        'credential_not_before_at_ms',
        'credential_expires_at_ms',
        'deployment_target_digest',
        'deployment_generation',
        'requested_by_type',
        'requested_by_id',
        'planned_at_ms',
        'expires_at_ms',
        'plan_digest',
        'preview_digest',
        'plan_json',
      ]),
      table('worker_credential_mutations', [
        'mutation_id',
        'operation',
        'credential_id',
        'credential_version',
        'expected_previous_version',
        'changed_by_type',
        'changed_by_id',
        'audit_event_id',
        'created_at_ms',
      ]),
      table('worker_credential_deliveries', [
        'delivery_id',
        'version',
        'state',
        'worker_id',
        'credential_id',
        'credential_version',
        'previous_credential_id',
        'secret_digest',
        'token_digest',
        'deployment_target_digest',
        'deployment_generation',
        'staged_at_ms',
        'credential_committed_at_ms',
        'published_at_ms',
        'publication_digest',
        'observed_at_ms',
        'observed_session_id',
        'observed_session_version',
        'previous_revoked_at_ms',
      ]),
      table('worker_credential_stage_discards', [
        'delivery_id',
        'version',
        'state',
        'worker_id',
        'credential_id',
        'credential_version',
        'previous_credential_id',
        'secret_digest',
        'token_digest',
        'deployment_target_digest',
        'deployment_generation',
        'staged_at_ms',
        'authorized_at_ms',
        'discarded_at_ms',
      ]),
      table('worker_execution_attestations', [
        'attestation_id',
        'run_id',
        'attempt_id',
        'sequence',
        'state',
        'worker_id',
        'worker_session_id',
        'worker_generation',
        'lease_token_digest',
        'lease_generation',
        'lease_version',
        'offer_id',
        'callback_sequence',
        'executor_handle',
        'journal_revision',
        'received_at_ms',
      ]),
      table('run_recovery_controls', [
        'target_kind',
        'target_id',
        'run_id',
        'attempt_id',
        'target_status',
        'target_created_at_ms',
        'observed_at_ms',
        'state',
        'claim_owner',
        'claim_token',
        'claim_version',
        'claim_expires_at_ms',
        'next_claim_at_ms',
        'failure_count',
        'created_at_ms',
        'updated_at_ms',
      ]),
      table('run_events', [
        'id',
        'run_id',
        'sequence',
        'type',
        'dedupe_key',
        'actor_type',
        'actor_id',
        'attempt_id',
        'step_run_id',
        'payload',
        'created_at_ms',
      ]),
      table('step_run_mutations', [
        'mutation_id',
        'mutation_digest',
        'run_id',
        'step_run_id',
        'step_run_digest',
        'event_id',
        'event_sequence',
        'run_version',
        'step_run_json',
        'committed_at_ms',
      ]),
      table('run_retry_policies', [
        'run_id',
        'max_attempts',
        'retry_on_lost',
        'safety',
        'backoff_base_ms',
        'backoff_max_ms',
        'next_attempt_at_ms',
        'version',
        'created_at_ms',
        'updated_at_ms',
      ]),
    ]),
    indexes: Object.freeze([
      'schema_migrations_pkey',
      'schema_capabilities_pkey',
      'projects_pkey',
      'ql3_projects_slug_uidx',
      'plugin_package_installs_pkey',
      'ql3_plugin_package_installs_quarantine_target_key',
      'ql3_plugin_package_installs_recovery_idx',
      'ql3_plugin_package_installs_project_history_idx',
      'ql3_plugin_package_installs_snapshot_source_uidx',
      'plugin_package_install_heads_pkey',
      'ql3_plugin_package_install_heads_install_uidx',
      'plugin_package_install_mutations_pkey',
      'ql3_plugin_package_install_mutations_result_idx',
      'plugin_package_materialized_revisions_pkey',
      'ql3_plugin_package_materialized_revision_generation_uidx',
      'ql3_plugin_package_materialized_revision_lock_idx',
      'ql3_plugin_package_materialized_revision_snapshot_source_uidx',
      'plugin_package_secret_bindings_pkey',
      'ql3_plugin_package_secret_binding_generation_uidx',
      'ql3_plugin_package_secret_binding_digest_uidx',
      'ql3_plugin_package_secret_binding_install_idx',
      'plugin_package_secret_binding_approval_plans_pkey',
      'ql3_plugin_package_secret_binding_approval_plan_digest_uidx',
      'ql3_plugin_package_secret_binding_approval_plan_target_idx',
      'ql3_plugin_package_secret_binding_approval_plan_expiry_idx',
      'plugin_package_secret_binding_transition_receipts_pkey',
      'ql3_package_secret_transition_receipt_transition_uidx',
      'ql3_package_secret_transition_receipt_digest_uidx',
      'ql3_package_secret_transition_receipt_install_idx',
      'plugin_package_secret_binding_transition_approval_plans_pkey',
      'ql3_pp_secret_transition_plan_digest_uidx',
      'ql3_pp_secret_transition_plan_target_uidx',
      'ql3_pp_secret_transition_plan_expiry_idx',
      'project_tool_definition_snapshots_pkey',
      'ql3_project_tool_snapshot_withdrawal_key',
      'ql3_project_tool_definition_snapshot_digest_uidx',
      'ql3_project_tool_definition_snapshot_current_idx',
      'project_tool_definition_snapshot_sources_pkey',
      'ql3_project_tool_definition_snapshot_source_generation_idx',
      'ql3_project_tool_definition_snapshot_source_install_idx',
      'plugin_package_quarantine_events_pkey',
      'ql3_plugin_package_quarantine_mutation_key',
      'ql3_plugin_package_quarantine_target_key',
      'ql3_plugin_package_quarantine_lock_idx',
      'ql3_plugin_package_quarantine_project_idx',
      'plugin_package_withdrawal_receipts_pkey',
      'ql3_plugin_package_withdrawal_receipt_key',
      'ql3_plugin_package_withdrawal_snapshot_idx',
      'plugin_package_withdrawal_tasks_pkey',
      'ql3_plugin_package_withdrawal_task_idx',
      'plugin_package_lifecycle_events_pkey',
      'ql3_plugin_package_lifecycle_mutation_key',
      'ql3_plugin_package_lifecycle_dispatch_key',
      'ql3_plugin_package_lifecycle_target_version_key',
      'ql3_plugin_package_lifecycle_project_idx',
      'plugin_package_lifecycle_heads_pkey',
      'ql3_plugin_package_lifecycle_head_event_key',
      'plugin_package_lifecycle_receipts_pkey',
      'ql3_plugin_package_lifecycle_receipt_key',
      'ql3_plugin_package_lifecycle_receipt_snapshot_idx',
      'plugin_package_lifecycle_tasks_pkey',
      'ql3_plugin_package_lifecycle_task_idx',
      'plugin_package_lifecycle_plans_pkey',
      'ql3_plugin_package_lifecycle_plan_digest_key',
      'ql3_plugin_package_lifecycle_plan_impact_key',
      'ql3_plugin_package_lifecycle_plan_expiry_idx',
      'plugin_package_automation_publications_pkey',
      'plugin_package_automation_disposition_events_pkey',
      'ql3_plugin_package_automation_publication_version_key',
      'ql3_plugin_package_automation_publication_previous_key',
      'ql3_plugin_package_automation_publication_generation_idx',
      'plugin_package_automation_publication_heads_pkey',
      'ql3_plugin_package_automation_publication_head_digest_key',
      'plugin_package_workflow_admissions_pkey',
      'plugin_package_workflow_admissions_plan_id_key',
      'plugin_package_workflow_admissions_run_id_key',
      'plugin_package_workflow_admissions_receipt_digest_key',
      'ql3_plugin_package_workflow_admission_plan_run_key',
      'ql3_plugin_package_workflow_admission_target_idx',
      'ql3_plugin_package_workflow_admission_workflow_history_idx',
      'plugin_package_workflow_admission_steps_pkey',
      'plugin_package_workflow_admission_steps_step_run_id_key',
      'plugin_package_workflow_admission_steps_mutation_id_key',
      'plugin_package_workflow_admission_steps_event_id_key',
      'ql3_plugin_package_workflow_admission_step_task_idx',
      'plugin_package_workflow_task_attempt_admissions_pkey',
      'plugin_package_workflow_task_attempt_admissions_attempt_id_key',
      'plugin_package_workflow_task_attempt_admissions_event_id_key',
      'plugin_package_workflow_task_attempt_admissions_epoch_key',
      'plugin_package_workflow_task_attempt_admissions_number_key',
      'ql3_pp_workflow_task_attempt_candidate_idx',
      'plugin_package_publisher_provenance_pkey',
      'ql3_plugin_package_publisher_provenance_digest_key',
      'ql3_plugin_package_publisher_provenance_signer_idx',
      'ql3_plugin_package_publisher_provenance_lock_idx',
      'plugin_package_publisher_revocation_receipts_pkey',
      'ql3_plugin_package_publisher_revocation_mutation_key',
      'ql3_plugin_package_publisher_revocation_signer_key',
      'plugin_package_publisher_revocation_impacts_pkey',
      'ql3_plugin_package_publisher_impact_digest_key',
      'plugin_package_publisher_revocation_impact_items_pkey',
      'ql3_plugin_package_publisher_impact_item_install_key',
      'ql3_plugin_package_publisher_impact_item_target_idx',
      'plugin_package_publisher_trust_snapshots_pkey',
      'plugin_package_publisher_trust_heads_pkey',
      'plugin_package_publisher_revocation_proposals_pkey',
      'ql3_plugin_package_publisher_revocation_proposal_digest_key',
      'ql3_plugin_package_publisher_revocation_proposal_project_idx',
      'ql3_plugin_package_publisher_revocation_proposal_signer_idx',
      'plugin_package_publisher_trust_transition_proposals_pkey',
      'ql3_pp_trust_transition_proposal_digest_key',
      'ql3_pp_trust_transition_proposal_project_idx',
      'ql3_pp_trust_transition_proposal_signer_idx',
      'plugin_package_publisher_trust_transition_receipts_pkey',
      'ql3_pp_trust_transition_receipt_proposal_key',
      'ql3_pp_trust_transition_receipt_digest_key',
      'ql3_pp_trust_transition_receipt_signer_idx',
      'plugin_package_task_ownerships_pkey',
      'ql3_plugin_package_task_ownership_package_idx',
      'plugin_package_task_reconciliations_pkey',
      'ql3_plugin_package_task_reconciliation_generation_uidx',
      'ql3_plugin_package_task_reconciliation_receipt_uidx',
      'ql3_plugin_package_task_reconciliation_lock_idx',
      'plugin_package_task_reconciliation_items_pkey',
      'ql3_plugin_package_task_reconciliation_item_task_idx',
      'approval_requests_pkey',
      'ql3_approval_requests_decision_uidx',
      'ql3_approval_requests_consumption_uidx',
      'ql3_approval_requests_dispatch_uidx',
      'ql3_approval_requests_pending_idx',
      'ql3_approval_requests_project_idx',
      'approved_action_dispatches_pkey',
      'ql3_approved_action_dispatch_lifecycle_key',
      'ql3_approved_action_dispatch_request_uidx',
      'ql3_approved_action_dispatch_project_idx',
      'approved_action_executions_pkey',
      'ql3_approved_action_execution_due_idx',
      'ql3_approved_action_execution_recovery_idx',
      'ql3_approved_action_execution_project_idx',
      'approved_action_manual_recovery_resolutions_pkey',
      'ql3_approved_action_manual_recovery_mutation_uidx',
      'ql3_approved_action_manual_recovery_digest_uidx',
      'ql3_approved_action_manual_recovery_project_idx',
      'plugin_package_install_proposals_pkey',
      'ql3_plugin_package_proposal_project_idx',
      'plugin_package_management_quota_buckets_pkey',
      'worker_credential_management_quota_buckets_pkey',
      'plugin_package_identity_keyset_ledger_pkey',
      'plugin_package_admission_receipts_pkey',
      'ql3_plugin_package_admission_install_uidx',
      'ql3_plugin_package_admission_audit_uidx',
      'ql3_plugin_package_admission_project_idx',
      'task_definitions_pkey',
      'task_definition_revisions_pkey',
      'ql3_task_definition_revisions_mutation_uidx',
      'ql3_task_definition_revisions_project_kind_idx',
      'task_execution_revisions_pkey',
      'ql3_task_execution_revisions_ref_uidx',
      'triggers_pkey',
      'ql3_triggers_task_uidx',
      'trigger_revisions_pkey',
      'ql3_trigger_revisions_mutation_uidx',
      'ql3_trigger_revisions_project_enabled_idx',
      'ql3_trigger_revisions_task_idx',
      'trigger_schedules_pkey',
      'ql3_trigger_schedules_due_idx',
      'ql3_trigger_schedules_claim_expiry_idx',
      'project_role_bindings_pkey',
      'ql3_project_role_bindings_current_idx',
      'ql3_project_role_bindings_mutation_uidx',
      'ql3_project_role_bindings_subject_idx',
      'identity_subjects_pkey',
      'ql3_identity_subjects_status_idx',
      'api_credentials_pkey',
      'ql3_api_credentials_current_idx',
      'ql3_api_credentials_subject_idx',
      'security_audit_events_pkey',
      'ql3_security_audit_events_occurred_idx',
      'ql3_security_audit_events_subject_idx',
      'ql3_security_audit_events_project_idx',
      'identity_subject_mutations_pkey',
      'ql3_identity_subject_mutations_subject_version_uidx',
      'ql3_identity_subject_mutations_actor_idx',
      'api_credential_mutations_pkey',
      'ql3_api_credential_mutations_credential_version_uidx',
      'ql3_api_credential_mutations_actor_idx',
      'runs_pkey',
      'ql3_runs_project_idempotency_uidx',
      'ql3_runs_project_created_idx',
      'ql3_runs_task_created_idx',
      'ql3_runs_dispatch_candidates_idx',
      'ql3_runs_runtime_recovery_idx',
      'step_runs_pkey',
      'ql3_step_runs_run_id_uidx',
      'ql3_step_runs_run_step_uidx',
      'ql3_step_runs_run_status_idx',
      'ql3_step_runs_recovery_idx',
      'tool_execution_trace_anchors_pkey',
      'ql3_tool_execution_trace_run_idx',
      'ql3_tool_execution_trace_step_idx',
      'tool_execution_audit_receipts_pkey',
      'ql3_tool_execution_audit_trace_uidx',
      'ql3_tool_execution_audit_run_idx',
      'ql3_tool_execution_audit_step_idx',
      'tool_execution_start_barriers_pkey',
      'ql3_tool_start_step_version_uidx',
      'ql3_tool_start_mutation_uidx',
      'ql3_tool_start_event_uidx',
      'ql3_tool_start_trace_uidx',
      'ql3_tool_start_audit_uidx',
      'ql3_tool_start_run_time_idx',
      'tool_invocation_input_artifacts_pkey',
      'ql3_tool_input_artifact_action_uidx',
      'ql3_tool_input_artifact_start_binding_uidx',
      'ql3_tool_input_artifact_project_time_idx',
      'tool_invocation_preview_artifacts_pkey',
      'ql3_tool_preview_artifact_action_uidx',
      'ql3_tool_preview_artifact_action_digest_uidx',
      'ql3_tool_preview_artifact_start_binding_uidx',
      'ql3_tool_preview_artifact_project_time_idx',
      'tool_execution_start_artifact_bindings_pkey',
      'ql3_tool_start_artifact_input_idx',
      'ql3_tool_start_artifact_preview_idx',
      'tool_execution_completions_pkey',
      'ql3_tool_completion_artifact_uidx',
      'ql3_tool_completion_mutation_uidx',
      'ql3_tool_completion_event_uidx',
      'ql3_tool_completion_step_version_uidx',
      'ql3_tool_completion_project_time_idx',
      'tool_execution_failure_completions_pkey',
      'ql3_tool_failure_completion_mutation_uidx',
      'ql3_tool_failure_completion_event_uidx',
      'ql3_tool_failure_completion_step_version_uidx',
      'ql3_tool_failure_completion_project_time_idx',
      'tool_result_key_catalog_generations_pkey',
      'ql3_tool_result_key_catalog_generation_digest_key',
      'ql3_tool_result_key_catalog_mutation_key',
      'ql3_tool_result_key_catalog_digest_key',
      'ql3_tool_result_key_catalog_current_idx',
      'tool_execution_result_key_bindings_pkey',
      'ql3_tool_result_key_binding_artifact_key',
      'ql3_tool_result_key_binding_digest_key',
      'ql3_tool_result_key_binding_catalog_idx',
      'tool_execution_result_rekey_overlays_pkey',
      'ql3_result_rekey_mutation_key',
      'ql3_result_rekey_digest_key',
      'ql3_result_rekey_artifact_revision_key',
      'ql3_result_rekey_artifact_revision_digest_key',
      'ql3_result_rekey_artifact_idx',
      'ql3_result_rekey_target_idx',
      'tool_execution_result_rekey_heads_pkey',
      'ql3_result_rekey_head_overlay_key',
      'ql3_result_rekey_head_digest_key',
      'ql3_result_rekey_head_target_idx',
      'tool_result_key_retirement_receipts_pkey',
      'ql3_result_retirement_mutation_key',
      'ql3_result_retirement_catalog_idx',
      'run_attempts_pkey',
      'ql3_run_attempts_run_attempt_uidx',
      'ql3_run_attempts_dispatch_candidates_idx',
      'ql3_run_attempts_recovery_idx',
      'ql3_run_attempts_lease_idx',
      'run_attempt_log_retention_controls_pkey',
      'ql3_run_log_retention_control_artifact_key',
      'ql3_run_log_retention_retry_idx',
      'ql3_run_log_retention_claim_expiry_idx',
      'run_attempt_log_artifact_tombstones_pkey',
      'ql3_run_log_tombstone_attempt_key',
      'ql3_run_log_tombstone_retired_idx',
      'ql3_run_log_retention_candidate_idx',
      'worker_sessions_pkey',
      'ql3_worker_sessions_available_idx',
      'run_dispatch_leases_pkey',
      'ql3_run_dispatch_leases_offer_uidx',
      'ql3_run_dispatch_leases_worker_active_idx',
      'ql3_run_dispatch_leases_expiry_idx',
      'worker_credentials_pkey',
      'ql3_worker_credentials_latest_idx',
      'worker_credential_management_plans_pkey',
      'ql3_worker_credential_management_plan_digest_key',
      'ql3_worker_credential_management_plan_delivery_key',
      'ql3_worker_credential_management_plan_expiry_idx',
      'worker_credential_mutations_pkey',
      'ql3_worker_credential_mutations_audit_uidx',
      'worker_credential_deliveries_pkey',
      'ql3_worker_credential_deliveries_recovery_idx',
      'ql3_worker_credential_deliveries_credential_uidx',
      'ql3_worker_credential_deliveries_credential_idx',
      'worker_credential_stage_discards_pkey',
      'ql3_worker_credential_stage_discards_recovery_idx',
      'worker_execution_attestations_pkey',
      'ql3_worker_execution_attestations_sequence_uidx',
      'ql3_worker_execution_attestations_exact_idx',
      'run_recovery_controls_pkey',
      'ql3_run_recovery_controls_available_idx',
      'ql3_run_recovery_controls_retry_idx',
      'ql3_run_recovery_controls_claim_expiry_idx',
      'run_events_pkey',
      'ql3_run_events_run_sequence_uidx',
      'ql3_run_events_run_dedupe_uidx',
      'ql3_run_events_run_created_idx',
      'step_run_mutations_pkey',
      'ql3_step_run_mutations_event_uidx',
      'ql3_step_run_mutations_step_idx',
      'run_retry_policies_pkey',
      'ql3_run_retry_policies_due_idx',
      'ql3_runs_lost_retry_idx',
    ]),
    checks: Object.freeze([
      'ql3_schema_migrations_dialect_check',
      'ql3_schema_migrations_checksum_check',
      'ql3_schema_migrations_applied_at_check',
      'ql3_schema_capabilities_version_check',
      'ql3_schema_capabilities_payload_check',
      'ql3_schema_capabilities_updated_at_check',
      'ql3_projects_id_check',
      'ql3_projects_name_check',
      'ql3_projects_slug_check',
      'ql3_projects_status_check',
      'ql3_projects_version_check',
      'ql3_projects_created_at_check',
      'ql3_projects_updated_at_check',
      'ql3_plugin_package_installs_identity_check',
      'ql3_plugin_package_installs_operation_check',
      'ql3_plugin_package_installs_state_check',
      'ql3_plugin_package_installs_version_check',
      'ql3_plugin_package_installs_digest_check',
      'ql3_plugin_package_installs_record_check',
      'ql3_plugin_package_secret_binding_identity_check',
      'ql3_plugin_package_secret_binding_digest_check',
      'ql3_plugin_package_secret_binding_json_check',
      'ql3_plugin_package_secret_binding_approval_plan_identity_check',
      'ql3_plugin_package_secret_binding_approval_plan_digest_check',
      'ql3_plugin_package_secret_binding_approval_plan_time_check',
      'ql3_plugin_package_secret_binding_approval_plan_json_check',
      'ql3_package_secret_transition_receipt_identity_check',
      'ql3_package_secret_transition_receipt_digest_check',
      'ql3_package_secret_transition_receipt_json_check',
      'ql3_pp_secret_transition_plan_identity_check',
      'ql3_pp_secret_transition_plan_digest_check',
      'ql3_pp_secret_transition_plan_time_check',
      'ql3_pp_secret_transition_plan_json_check',
      'ql3_plugin_package_quarantine_identity_check',
      'ql3_plugin_package_quarantine_state_check',
      'ql3_plugin_package_quarantine_subject_check',
      'ql3_plugin_package_quarantine_digest_check',
      'ql3_plugin_package_quarantine_json_check',
      'ql3_plugin_package_quarantine_time_check',
      'ql3_plugin_package_withdrawal_disposition_check',
      'ql3_plugin_package_withdrawal_digest_check',
      'ql3_plugin_package_withdrawal_json_check',
      'ql3_plugin_package_withdrawal_time_check',
      'ql3_plugin_package_withdrawal_task_identity_check',
      'ql3_plugin_package_withdrawal_task_digest_check',
      'ql3_plugin_package_lifecycle_identity_check',
      'ql3_plugin_package_lifecycle_expectation_check',
      'ql3_plugin_package_lifecycle_origin_check',
      'ql3_plugin_package_lifecycle_subject_check',
      'ql3_plugin_package_lifecycle_digest_check',
      'ql3_plugin_package_lifecycle_json_check',
      'ql3_plugin_package_lifecycle_time_check',
      'ql3_plugin_package_lifecycle_head_state_check',
      'ql3_plugin_package_lifecycle_head_digest_check',
      'ql3_plugin_package_lifecycle_receipt_state_check',
      'ql3_plugin_package_lifecycle_receipt_bounds_check',
      'ql3_plugin_package_lifecycle_receipt_digest_check',
      'ql3_plugin_package_lifecycle_receipt_json_check',
      'ql3_plugin_package_lifecycle_task_transition_check',
      'ql3_plugin_package_lifecycle_task_digest_check',
      'ql3_plugin_package_lifecycle_plan_identity_check',
      'ql3_plugin_package_lifecycle_plan_digest_check',
      'ql3_plugin_package_lifecycle_plan_time_check',
      'ql3_plugin_package_lifecycle_plan_json_check',
      'ql3_plugin_package_automation_publication_identity_check',
      'ql3_plugin_package_automation_publication_digest_check',
      'ql3_plugin_package_automation_publication_json_check',
      'ql3_plugin_package_automation_publication_head_state_check',
      'ql3_plugin_package_automation_disposition_kind_check',
      'ql3_plugin_package_automation_disposition_digest_check',
      'ql3_plugin_package_workflow_admission_identity_check',
      'ql3_plugin_package_workflow_admission_digest_check',
      'ql3_plugin_package_workflow_admission_json_check',
      'ql3_plugin_package_workflow_admission_step_identity_check',
      'ql3_pp_workflow_task_attempt_identity_check',
      'ql3_pp_workflow_task_attempt_counter_check',
      'ql3_plugin_package_workflow_task_attempt_admission_digest_check',
      'ql3_plugin_package_workflow_task_attempt_admission_json_check',
      'ql3_plugin_package_publisher_provenance_identity_check',
      'ql3_plugin_package_publisher_provenance_digest_check',
      'ql3_plugin_package_publisher_provenance_time_check',
      'ql3_plugin_package_publisher_provenance_json_check',
      'ql3_plugin_package_publisher_revocation_identity_check',
      'ql3_plugin_package_publisher_revocation_digest_check',
      'ql3_plugin_package_publisher_revocation_time_check',
      'ql3_plugin_package_publisher_revocation_json_check',
      'ql3_plugin_package_publisher_impact_digest_check',
      'ql3_plugin_package_publisher_impact_count_check',
      'ql3_plugin_package_publisher_impact_json_check',
      'ql3_plugin_package_publisher_impact_item_identity_check',
      'ql3_plugin_package_publisher_trust_snapshot_identity_check',
      'ql3_plugin_package_publisher_trust_snapshot_digest_check',
      'ql3_plugin_package_publisher_trust_snapshot_count_check',
      'ql3_plugin_package_publisher_trust_snapshot_json_check',
      'ql3_plugin_package_publisher_trust_head_identity_check',
      'ql3_plugin_package_publisher_trust_head_digest_check',
      'ql3_plugin_package_publisher_trust_head_time_check',
      'ql3_plugin_package_publisher_trust_head_json_check',
      'ql3_plugin_package_publisher_revocation_proposal_identity_check',
      'ql3_plugin_package_publisher_revocation_proposal_digest_check',
      'ql3_plugin_package_publisher_revocation_proposal_time_check',
      'ql3_plugin_package_publisher_revocation_proposal_json_check',
      'ql3_pp_trust_transition_proposal_identity_check',
      'ql3_pp_trust_transition_proposal_digest_check',
      'ql3_pp_trust_transition_proposal_time_check',
      'ql3_pp_trust_transition_proposal_json_check',
      'ql3_pp_trust_transition_receipt_identity_check',
      'ql3_pp_trust_transition_receipt_transition_check',
      'ql3_pp_trust_transition_receipt_json_check',
      'ql3_plugin_package_installs_time_check',
      'ql3_plugin_package_install_heads_identity_check',
      'ql3_plugin_package_install_mutations_identity_check',
      'ql3_plugin_package_install_mutations_digest_check',
      'ql3_plugin_package_install_mutations_time_check',
      'ql3_plugin_package_materialized_revision_identity_check',
      'ql3_plugin_package_materialized_revision_digest_check',
      'ql3_plugin_package_materialized_revision_json_check',
      'ql3_plugin_package_materialized_revision_time_check',
      'ql3_project_tool_definition_snapshot_identity_check',
      'ql3_project_tool_definition_snapshot_digest_check',
      'ql3_project_tool_definition_snapshot_json_check',
      'ql3_project_tool_definition_snapshot_time_check',
      'ql3_project_tool_definition_snapshot_source_identity_check',
      'ql3_project_tool_definition_snapshot_source_digest_check',
      'ql3_plugin_package_task_ownership_identity_check',
      'ql3_plugin_package_task_ownership_digest_check',
      'ql3_plugin_package_task_ownership_namespace_check',
      'ql3_plugin_package_task_ownership_time_check',
      'ql3_plugin_package_task_reconciliation_identity_check',
      'ql3_plugin_package_task_reconciliation_digest_check',
      'ql3_plugin_package_task_reconciliation_json_check',
      'ql3_plugin_package_task_reconciliation_time_check',
      'ql3_plugin_package_task_reconciliation_item_identity_check',
      'ql3_plugin_package_task_reconciliation_item_disposition_check',
      'ql3_plugin_package_task_reconciliation_item_digest_check',
      'ql3_approval_requests_identity_check',
      'ql3_approval_requests_state_version_check',
      'ql3_approval_requests_digest_check',
      'ql3_approval_requests_subject_check',
      'ql3_approval_requests_mutation_tuple_check',
      'ql3_approval_requests_json_check',
      'ql3_approval_requests_time_check',
      'ql3_approved_action_dispatch_identity_check',
      'ql3_approved_action_dispatch_digest_check',
      'ql3_approved_action_dispatch_json_check',
      'ql3_approved_action_dispatch_time_check',
      'ql3_approved_action_execution_state_check',
      'ql3_approved_action_execution_lease_check',
      'ql3_approved_action_execution_result_check',
      'ql3_approved_action_execution_digest_check',
      'ql3_approved_action_execution_json_check',
      'ql3_approved_action_execution_time_check',
      'ql3_approved_action_manual_recovery_identity_check',
      'ql3_approved_action_manual_recovery_digest_check',
      'ql3_approved_action_manual_recovery_time_check',
      'ql3_approved_action_manual_recovery_json_check',
      'ql3_plugin_package_proposal_identity_check',
      'ql3_plugin_package_proposal_digest_check',
      'ql3_plugin_package_proposal_json_check',
      'ql3_plugin_package_proposal_time_check',
      'ql3_plugin_package_management_quota_identity_check',
      'ql3_plugin_package_management_quota_operation_check',
      'ql3_plugin_package_management_quota_window_check',
      'ql3_plugin_package_management_quota_receipts_check',
      'ql3_worker_credential_management_quota_identity_check',
      'ql3_worker_credential_management_quota_operation_check',
      'ql3_worker_credential_management_quota_window_check',
      'ql3_worker_credential_management_quota_receipts_check',
      'ql3_plugin_package_identity_keyset_authority_check',
      'ql3_plugin_package_identity_keyset_generation_check',
      'ql3_plugin_package_identity_keyset_digest_check',
      'ql3_plugin_package_identity_keyset_trust_domain_check',
      'ql3_plugin_package_identity_keyset_keys_check',
      'ql3_plugin_package_admission_identity_check',
      'ql3_plugin_package_admission_digest_check',
      'ql3_plugin_package_admission_json_check',
      'ql3_plugin_package_admission_time_check',
      'ql3_task_definitions_id_check',
      'ql3_task_definitions_revision_check',
      'ql3_task_definitions_time_check',
      'ql3_task_definition_revisions_revision_check',
      'ql3_task_definition_revisions_name_check',
      'ql3_task_definition_revisions_kind_check',
      'ql3_task_definition_revisions_spec_check',
      'ql3_task_definition_revisions_labels_check',
      'ql3_task_definition_revisions_digest_check',
      'ql3_task_definition_revisions_created_check',
      'ql3_task_execution_revisions_identity_check',
      'ql3_task_execution_revisions_executor_check',
      'ql3_task_execution_revisions_plan_check',
      'ql3_task_execution_revisions_digest_check',
      'ql3_task_execution_revisions_created_check',
      'ql3_triggers_id_check',
      'ql3_triggers_revision_check',
      'ql3_triggers_time_check',
      'ql3_trigger_revisions_revision_check',
      'ql3_trigger_revisions_task_digest_check',
      'ql3_trigger_revisions_spec_check',
      'ql3_trigger_revisions_digest_check',
      'ql3_trigger_revisions_created_check',
      'ql3_trigger_schedules_revision_check',
      'ql3_trigger_schedules_cursor_check',
      'ql3_trigger_schedules_last_check',
      'ql3_trigger_schedules_version_check',
      'ql3_trigger_schedules_claim_owner_check',
      'ql3_trigger_schedules_claim_shape_check',
      'ql3_trigger_schedules_updated_check',
      'ql3_project_role_bindings_subject_type_check',
      'ql3_project_role_bindings_subject_id_check',
      'ql3_project_role_bindings_version_check',
      'ql3_project_role_bindings_state_check',
      'ql3_project_role_bindings_role_state_check',
      'ql3_project_role_bindings_mutation_id_check',
      'ql3_project_role_bindings_changed_by_type_check',
      'ql3_project_role_bindings_changed_by_id_check',
      'ql3_project_role_bindings_created_at_check',
      'ql3_identity_subjects_type_check',
      'ql3_identity_subjects_id_check',
      'ql3_identity_subjects_status_check',
      'ql3_identity_subjects_version_check',
      'ql3_identity_subjects_created_at_check',
      'ql3_identity_subjects_updated_at_check',
      'ql3_api_credentials_id_check',
      'ql3_api_credentials_version_check',
      'ql3_api_credentials_state_check',
      'ql3_api_credentials_subject_type_check',
      'ql3_api_credentials_subject_id_check',
      'ql3_api_credentials_pepper_key_id_check',
      'ql3_api_credentials_secret_digest_check',
      'ql3_api_credentials_created_at_check',
      'ql3_api_credentials_not_before_check',
      'ql3_api_credentials_expires_at_check',
      'ql3_security_audit_events_request_id_check',
      'ql3_security_audit_events_operation_id_check',
      'ql3_security_audit_events_project_id_check',
      'ql3_security_audit_events_subject_type_check',
      'ql3_security_audit_events_subject_id_check',
      'ql3_security_audit_events_authentication_id_check',
      'ql3_security_audit_events_outcome_check',
      'ql3_security_audit_events_reasons_check',
      'ql3_security_audit_events_project_version_check',
      'ql3_security_audit_events_binding_version_check',
      'ql3_security_audit_events_occurred_at_check',
      'ql3_security_audit_events_identity_check',
      'ql3_security_audit_events_fence_check',
      'ql3_identity_subject_mutations_operation_check',
      'ql3_identity_subject_mutations_subject_type_check',
      'ql3_identity_subject_mutations_subject_id_check',
      'ql3_identity_subject_mutations_version_check',
      'ql3_identity_subject_mutations_previous_version_check',
      'ql3_identity_subject_mutations_status_check',
      'ql3_identity_subject_mutations_changed_by_type_check',
      'ql3_identity_subject_mutations_changed_by_id_check',
      'ql3_identity_subject_mutations_identity_created_at_check',
      'ql3_identity_subject_mutations_created_at_check',
      'ql3_identity_subject_mutations_version_fence_check',
      'ql3_identity_subject_mutations_transition_check',
      'ql3_identity_subject_mutations_audit_identity_check',
      'ql3_api_credential_mutations_operation_check',
      'ql3_api_credential_mutations_id_check',
      'ql3_api_credential_mutations_version_check',
      'ql3_api_credential_mutations_previous_version_check',
      'ql3_api_credential_mutations_state_check',
      'ql3_api_credential_mutations_subject_type_check',
      'ql3_api_credential_mutations_subject_id_check',
      'ql3_api_credential_mutations_subject_status_check',
      'ql3_api_credential_mutations_changed_by_type_check',
      'ql3_api_credential_mutations_changed_by_id_check',
      'ql3_api_credential_mutations_created_at_check',
      'ql3_api_credential_mutations_version_fence_check',
      'ql3_api_credential_mutations_transition_check',
      'ql3_api_credential_mutations_audit_identity_check',
      'ql3_runs_legacy_cron_id_check',
      'ql3_runs_execution_owner_check',
      'ql3_runs_scheduled_for_check',
      'ql3_runs_status_check',
      'ql3_runs_version_check',
      'ql3_runs_event_sequence_check',
      'ql3_runs_created_at_check',
      'ql3_runs_queued_at_check',
      'ql3_runs_started_at_check',
      'ql3_runs_finished_at_check',
      'ql3_runs_cancel_requested_at_check',
      'ql3_runs_cancel_reason_check',
      'ql3_run_attempts_attempt_check',
      'ql3_run_attempts_status_check',
      'ql3_run_attempts_pid_check',
      'ql3_run_attempts_lease_expiry_check',
      'ql3_run_attempts_worker_session_id_check',
      'ql3_run_attempts_worker_generation_check',
      'ql3_run_attempts_lease_generation_check',
      'ql3_run_attempts_lease_version_check',
      'ql3_run_attempts_lease_token_digest_check',
      'ql3_run_attempts_offer_id_check',
      'ql3_run_attempts_remote_fence_shape_check',
      'ql3_run_attempts_deadline_check',
      'ql3_run_attempts_callback_sequence_check',
      'ql3_run_attempts_created_at_check',
      'ql3_run_attempts_started_at_check',
      'ql3_run_attempts_finished_at_check',
      'ql3_run_log_retention_control_identity_check',
      'ql3_run_log_retention_control_time_check',
      'ql3_run_log_retention_control_state_check',
      'ql3_run_log_retention_control_claim_owner_check',
      'ql3_run_log_retention_control_claim_token_check',
      'ql3_run_log_retention_control_claim_version_check',
      'ql3_run_log_retention_control_claim_expiry_check',
      'ql3_run_log_retention_control_next_claim_check',
      'ql3_run_log_retention_control_failure_count_check',
      'ql3_run_log_retention_control_failure_code_check',
      'ql3_run_log_retention_control_state_shape_check',
      'ql3_run_log_tombstone_identity_check',
      'ql3_run_log_tombstone_time_check',
      'ql3_run_log_tombstone_disposition_check',
      'ql3_run_log_tombstone_size_check',
      'ql3_run_log_tombstone_truncation_check',
      'ql3_run_log_tombstone_digest_check',
      'ql3_worker_sessions_worker_id_check',
      'ql3_worker_sessions_session_id_check',
      'ql3_worker_sessions_generation_check',
      'ql3_worker_sessions_status_check',
      'ql3_worker_sessions_version_check',
      'ql3_worker_sessions_capabilities_check',
      'ql3_worker_sessions_capabilities_hash_check',
      'ql3_worker_sessions_concurrency_check',
      'ql3_worker_sessions_timestamps_check',
      'ql3_worker_sessions_status_capacity_check',
      'ql3_run_dispatch_leases_status_check',
      'ql3_run_dispatch_leases_version_check',
      'ql3_run_dispatch_leases_generation_check',
      'ql3_run_dispatch_leases_worker_generation_check',
      'ql3_run_dispatch_leases_token_digest_check',
      'ql3_run_dispatch_leases_offer_id_check',
      'ql3_run_dispatch_leases_timestamps_check',
      'ql3_run_dispatch_leases_state_shape_check',
      'ql3_worker_credentials_id_check',
      'ql3_worker_credentials_version_check',
      'ql3_worker_credentials_state_check',
      'ql3_worker_credentials_worker_id_check',
      'ql3_worker_credentials_digest_check',
      'ql3_worker_credentials_lifetime_check',
      'ql3_worker_credential_management_plan_identity_check',
      'ql3_worker_credential_management_plan_action_check',
      'ql3_worker_credential_management_plan_digest_check',
      'ql3_worker_credential_management_plan_time_check',
      'ql3_worker_credential_management_plan_json_check',
      'ql3_worker_credential_mutations_id_check',
      'ql3_worker_credential_mutations_operation_check',
      'ql3_worker_credential_mutations_version_check',
      'ql3_worker_credential_mutations_actor_check',
      'ql3_worker_credential_mutations_created_at_check',
      'ql3_worker_execution_attestations_id_check',
      'ql3_worker_execution_attestations_sequence_check',
      'ql3_worker_execution_attestations_state_check',
      'ql3_worker_execution_attestations_worker_id_check',
      'ql3_worker_execution_attestations_session_id_check',
      'ql3_worker_execution_attestations_generation_check',
      'ql3_worker_execution_attestations_digest_check',
      'ql3_worker_execution_attestations_offer_check',
      'ql3_worker_execution_attestations_callback_check',
      'ql3_worker_execution_attestations_handle_check',
      'ql3_worker_execution_attestations_journal_check',
      'ql3_worker_execution_attestations_received_at_check',
      'ql3_run_recovery_controls_target_kind_check',
      'ql3_run_recovery_controls_target_id_check',
      'ql3_run_recovery_controls_target_shape_check',
      'ql3_run_recovery_controls_target_created_at_check',
      'ql3_run_recovery_controls_observed_at_check',
      'ql3_run_recovery_controls_state_check',
      'ql3_run_recovery_controls_claim_owner_check',
      'ql3_run_recovery_controls_claim_token_check',
      'ql3_run_recovery_controls_claim_version_check',
      'ql3_run_recovery_controls_claim_expires_at_check',
      'ql3_run_recovery_controls_next_claim_at_check',
      'ql3_run_recovery_controls_failure_count_check',
      'ql3_run_recovery_controls_created_at_check',
      'ql3_run_recovery_controls_updated_at_check',
      'ql3_run_recovery_controls_state_shape_check',
      'ql3_run_events_sequence_check',
      'ql3_run_events_actor_type_check',
      'ql3_run_events_payload_check',
      'ql3_run_events_created_at_check',
      'ql3_run_retry_policies_max_attempts_check',
      'ql3_run_retry_policies_safety_check',
      'ql3_run_retry_policies_backoff_base_check',
      'ql3_run_retry_policies_backoff_max_check',
      'ql3_run_retry_policies_next_attempt_check',
      'ql3_run_retry_policies_version_check',
      'ql3_run_retry_policies_created_at_check',
      'ql3_run_retry_policies_updated_at_check',
      'ql3_worker_credential_deliveries_version_check',
      'ql3_worker_credential_deliveries_id_check',
      'ql3_worker_credential_deliveries_state_check',
      'ql3_worker_credential_deliveries_worker_check',
      'ql3_worker_credential_deliveries_credential_check',
      'ql3_worker_credential_deliveries_digest_check',
      'ql3_worker_credential_deliveries_generation_check',
      'ql3_worker_credential_deliveries_session_check',
      'ql3_worker_credential_deliveries_time_check',
      'ql3_worker_credential_deliveries_state_shape_check',
      'ql3_worker_credential_stage_discards_version_check',
      'ql3_worker_credential_stage_discards_id_check',
      'ql3_worker_credential_stage_discards_state_check',
      'ql3_worker_credential_stage_discards_worker_check',
      'ql3_worker_credential_stage_discards_credential_check',
      'ql3_worker_credential_stage_discards_digest_check',
      'ql3_worker_credential_stage_discards_generation_check',
      'ql3_worker_credential_stage_discards_time_check',
      'ql3_worker_credential_stage_discards_state_shape_check',
      'ql3_step_runs_identity_check',
      'ql3_step_runs_kind_check',
      'ql3_step_runs_status_check',
      'ql3_step_runs_digest_check',
      'ql3_step_runs_counter_check',
      'ql3_step_runs_reference_check',
      'ql3_step_runs_time_check',
      'ql3_step_runs_state_shape_check',
      'ql3_step_runs_approval_shape_check',
      'ql3_step_runs_result_shape_check',
      'ql3_step_runs_mutation_identity_check',
      'ql3_step_runs_json_check',
      'ql3_tool_execution_trace_identity_check',
      'ql3_tool_execution_trace_digest_check',
      'ql3_tool_execution_trace_time_check',
      'ql3_tool_execution_trace_json_check',
      'ql3_tool_execution_audit_identity_check',
      'ql3_tool_execution_audit_digest_check',
      'ql3_tool_execution_audit_time_check',
      'ql3_tool_execution_audit_json_check',
      'ql3_tool_execution_audit_receipt_json_check',
      'ql3_tool_start_identity_check',
      'ql3_tool_start_version_time_check',
      'ql3_tool_start_digest_check',
      'ql3_tool_start_json_check',
      'ql3_tool_input_artifact_identity_check',
      'ql3_tool_input_artifact_digest_check',
      'ql3_tool_input_artifact_budget_check',
      'ql3_tool_input_artifact_json_check',
      'ql3_tool_preview_artifact_identity_check',
      'ql3_tool_preview_artifact_digest_check',
      'ql3_tool_preview_artifact_budget_check',
      'ql3_tool_preview_artifact_json_check',
      'ql3_tool_start_artifact_identity_check',
      'ql3_tool_start_artifact_digest_check',
      'ql3_tool_start_artifact_time_check',
      'ql3_tool_completion_identity_check',
      'ql3_tool_completion_version_check',
      'ql3_tool_completion_digest_check',
      'ql3_tool_completion_budget_check',
      'ql3_tool_completion_json_check',
      'ql3_tool_failure_completion_identity_check',
      'ql3_tool_failure_completion_version_check',
      'ql3_tool_failure_completion_digest_check',
      'ql3_tool_failure_completion_fact_check',
      'ql3_tool_failure_completion_budget_check',
      'ql3_tool_failure_completion_json_check',
      'ql3_tool_result_key_catalog_authority_check',
      'ql3_tool_result_key_catalog_generation_check',
      'ql3_tool_result_key_catalog_identity_check',
      'ql3_tool_result_key_catalog_digest_check',
      'ql3_tool_result_key_catalog_budget_check',
      'ql3_tool_result_key_catalog_json_check',
      'ql3_result_rekey_revision_check',
      'ql3_result_rekey_authority_check',
      'ql3_result_rekey_identity_check',
      'ql3_result_rekey_digest_check',
      'ql3_result_rekey_budget_check',
      'ql3_result_rekey_json_check',
      'ql3_result_rekey_head_identity_check',
      'ql3_result_rekey_head_digest_check',
      'ql3_result_retirement_authority_check',
      'ql3_result_retirement_identity_check',
      'ql3_result_retirement_count_check',
      'ql3_result_retirement_digest_check',
      'ql3_result_retirement_json_check',
      'ql3_tool_result_key_binding_authority_check',
      'ql3_tool_result_key_binding_identity_check',
      'ql3_tool_result_key_binding_digest_check',
      'ql3_step_run_mutations_identity_check',
      'ql3_step_run_mutations_digest_check',
      'ql3_step_run_mutations_counter_check',
      'ql3_step_run_mutations_json_check',
    ]),
    foreignKeys: Object.freeze([
      'ql3_schema_capabilities_migration_fk',
      'ql3_plugin_package_installs_project_fk',
      'ql3_plugin_package_install_heads_project_fk',
      'ql3_plugin_package_install_heads_install_fk',
      'ql3_plugin_package_install_mutations_install_fk',
      'ql3_plugin_package_materialized_revision_project_fk',
      'ql3_plugin_package_secret_binding_project_fk',
      'ql3_plugin_package_secret_binding_install_fk',
      'ql3_plugin_package_secret_binding_approval_plan_project_fk',
      'ql3_plugin_package_secret_binding_approval_plan_install_fk',
      'ql3_plugin_package_secret_binding_transition_receipt_project_fk',
      'ql3_plugin_package_secret_binding_transition_receipt_install_fk',
      'ql3_pp_secret_transition_plan_project_fk',
      'ql3_pp_secret_transition_plan_install_fk',
      'ql3_project_tool_definition_snapshot_project_fk',
      'ql3_project_tool_definition_snapshot_source_snapshot_fk',
      'ql3_project_tool_definition_snapshot_source_install_fk',
      'ql3_project_tool_definition_snapshot_source_revision_fk',
      'ql3_plugin_package_quarantine_install_fk',
      'ql3_plugin_package_withdrawal_event_fk',
      'ql3_plugin_package_withdrawal_snapshot_fk',
      'ql3_plugin_package_withdrawal_task_receipt_fk',
      'ql3_plugin_package_withdrawal_task_previous_fk',
      'ql3_plugin_package_withdrawal_task_disabled_fk',
      'ql3_plugin_package_lifecycle_install_fk',
      'ql3_plugin_package_lifecycle_dispatch_fk',
      'ql3_plugin_package_lifecycle_previous_event_fk',
      'ql3_plugin_package_lifecycle_head_install_fk',
      'ql3_plugin_package_lifecycle_head_event_fk',
      'ql3_plugin_package_lifecycle_receipt_event_fk',
      'ql3_plugin_package_lifecycle_receipt_snapshot_fk',
      'ql3_plugin_package_lifecycle_task_receipt_fk',
      'ql3_plugin_package_lifecycle_task_previous_fk',
      'ql3_plugin_package_lifecycle_task_current_fk',
      'ql3_plugin_package_lifecycle_plan_install_fk',
      'ql3_plugin_package_automation_publication_revision_fk',
      'ql3_plugin_package_automation_publication_previous_fk',
      'ql3_plugin_package_automation_publication_disposition_fk',
      'ql3_plugin_package_automation_publication_head_publication_fk',
      'ql3_plugin_package_workflow_admission_run_fk',
      'ql3_plugin_package_workflow_admission_publication_fk',
      'ql3_plugin_package_workflow_admission_step_admission_fk',
      'ql3_plugin_package_workflow_admission_step_run_fk',
      'ql3_plugin_package_workflow_admission_step_mutation_fk',
      'ql3_plugin_package_workflow_admission_step_event_fk',
      'ql3_plugin_package_workflow_task_attempt_admission_plan_fk',
      'ql3_plugin_package_workflow_task_attempt_admission_step_fk',
      'ql3_plugin_package_workflow_task_attempt_admission_attempt_fk',
      'ql3_plugin_package_workflow_task_attempt_admission_event_fk',
      'ql3_pp_workflow_task_attempt_reconciliation_fk',
      'ql3_plugin_package_workflow_task_attempt_admission_execution_fk',
      'ql3_plugin_package_publisher_provenance_install_fk',
      'ql3_plugin_package_publisher_impact_receipt_fk',
      'ql3_plugin_package_publisher_impact_item_impact_fk',
      'ql3_plugin_package_publisher_impact_item_provenance_fk',
      'ql3_plugin_package_publisher_impact_item_install_fk',
      'ql3_plugin_package_publisher_trust_head_snapshot_fk',
      'ql3_plugin_package_publisher_trust_head_effective_snapshot_fk',
      'ql3_plugin_package_publisher_revocation_proposal_project_fk',
      'ql3_plugin_package_publisher_revocation_proposal_head_fk',
      'ql3_pp_trust_transition_proposal_project_fk',
      'ql3_pp_trust_transition_proposal_head_fk',
      'ql3_pp_trust_transition_proposal_previous_fk',
      'ql3_pp_trust_transition_proposal_current_fk',
      'ql3_pp_trust_transition_receipt_dispatch_fk',
      'ql3_pp_trust_transition_receipt_proposal_fk',
      'ql3_pp_trust_transition_receipt_head_fk',
      'ql3_pp_trust_transition_receipt_previous_fk',
      'ql3_pp_trust_transition_receipt_current_fk',
      'ql3_plugin_package_task_ownership_project_fk',
      'ql3_plugin_package_task_ownership_task_fk',
      'ql3_plugin_package_task_reconciliation_materialized_fk',
      'ql3_plugin_package_task_reconciliation_item_reconciliation_fk',
      'ql3_approval_requests_project_fk',
      'ql3_approved_action_dispatch_request_fk',
      'ql3_approved_action_dispatch_project_fk',
      'ql3_approved_action_execution_dispatch_fk',
      'ql3_approved_action_manual_recovery_dispatch_fk',
      'ql3_approved_action_manual_recovery_project_fk',
      'ql3_approved_action_manual_recovery_audit_fk',
      'ql3_approved_action_execution_project_fk',
      'ql3_plugin_package_proposal_project_fk',
      'ql3_plugin_package_management_quota_project_fk',
      'ql3_worker_credential_management_quota_project_fk',
      'ql3_plugin_package_admission_dispatch_fk',
      'ql3_plugin_package_admission_request_fk',
      'ql3_plugin_package_admission_project_fk',
      'ql3_plugin_package_admission_install_fk',
      'ql3_plugin_package_admission_audit_fk',
      'ql3_task_definitions_project_fk',
      'ql3_task_definition_revisions_head_fk',
      'ql3_task_execution_revisions_source_fk',
      'ql3_triggers_project_fk',
      'ql3_triggers_task_fk',
      'ql3_trigger_revisions_head_fk',
      'ql3_trigger_revisions_task_revision_fk',
      'ql3_trigger_schedules_revision_fk',
      'ql3_project_role_bindings_project_fk',
      'ql3_api_credentials_subject_fk',
      'ql3_identity_subject_mutations_subject_fk',
      'ql3_identity_subject_mutations_audit_fk',
      'ql3_api_credential_mutations_credential_fk',
      'ql3_api_credential_mutations_subject_fk',
      'ql3_api_credential_mutations_audit_fk',
      'ql3_runs_parent_fk',
      'ql3_runs_retry_of_fk',
      'ql3_step_runs_run_fk',
      'ql3_step_runs_parent_fk',
      'ql3_tool_execution_trace_step_fk',
      'ql3_tool_execution_audit_event_fk',
      'ql3_tool_execution_audit_trace_fk',
      'ql3_tool_execution_audit_step_fk',
      'ql3_tool_start_step_fk',
      'ql3_tool_start_mutation_fk',
      'ql3_tool_start_event_fk',
      'ql3_tool_start_trace_fk',
      'ql3_tool_start_audit_fk',
      'ql3_tool_input_artifact_project_fk',
      'ql3_tool_preview_artifact_project_fk',
      'ql3_tool_start_artifact_barrier_fk',
      'ql3_tool_start_input_artifact_fk',
      'ql3_tool_start_preview_artifact_fk',
      'ql3_tool_completion_start_fk',
      'ql3_tool_completion_step_fk',
      'ql3_tool_completion_mutation_fk',
      'ql3_tool_completion_event_fk',
      'ql3_tool_failure_completion_start_fk',
      'ql3_tool_failure_completion_step_fk',
      'ql3_tool_failure_completion_mutation_fk',
      'ql3_tool_failure_completion_event_fk',
      'ql3_tool_result_key_catalog_previous_fk',
      'ql3_tool_result_key_binding_completion_fk',
      'ql3_tool_result_key_binding_artifact_fk',
      'ql3_tool_result_key_binding_catalog_fk',
      'ql3_result_rekey_artifact_fk',
      'ql3_result_rekey_binding_fk',
      'ql3_result_rekey_previous_fk',
      'ql3_result_rekey_catalog_fk',
      'ql3_result_rekey_head_overlay_fk',
      'ql3_result_retirement_catalog_fk',
      'ql3_run_attempts_run_fk',
      'ql3_run_attempts_step_run_fk',
      'ql3_run_log_retention_control_attempt_fk',
      'ql3_run_log_retention_control_run_fk',
      'ql3_run_log_tombstone_attempt_fk',
      'ql3_run_log_tombstone_run_fk',
      'ql3_run_dispatch_leases_attempt_fk',
      'ql3_run_dispatch_leases_run_fk',
      'ql3_run_dispatch_leases_worker_fk',
      'ql3_worker_credential_management_plan_project_fk',
      'ql3_worker_credential_mutations_credential_fk',
      'ql3_worker_credential_mutations_audit_fk',
      'ql3_worker_credential_deliveries_mutation_fk',
      'ql3_worker_credential_deliveries_credential_fk',
      'ql3_worker_execution_attestations_run_fk',
      'ql3_worker_execution_attestations_attempt_fk',
      'ql3_worker_execution_attestations_worker_fk',
      'ql3_run_recovery_controls_run_fk',
      'ql3_run_recovery_controls_attempt_fk',
      'ql3_run_events_run_fk',
      'ql3_run_events_attempt_fk',
      'ql3_run_events_step_run_fk',
      'ql3_step_run_mutations_step_fk',
      'ql3_step_run_mutations_event_fk',
      'ql3_run_retry_policies_run_fk',
    ]),
    functions: Object.freeze([
      Object.freeze({
        name: 'resolve_approved_action_manual_recovery',
        identityArguments:
          'p_resolution_json jsonb, p_next_execution_json jsonb, p_audit_json jsonb',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'plugin_package_secret_binding_transition_snapshot',
        identityArguments:
          'p_project_id character varying, p_package_name character varying',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'create_plugin_package_secret_transition_plan',
        identityArguments: 'p_plan_json jsonb',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'plugin_package_secret_binding_planning_snapshot',
        identityArguments:
          'p_project_id character varying, p_package_name character varying',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'create_plugin_package_secret_binding_approval_plan',
        identityArguments: 'p_plan_json jsonb',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'enforce_plugin_package_secret_binding_target',
        identityArguments: '',
        owner: 'ql3_migration',
        securityDefiner: false,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'enforce_plugin_package_secret_binding_transition_receipt_target',
        identityArguments: '',
        owner: 'ql3_migration',
        securityDefiner: false,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'enforce_plugin_package_secret_materialization',
        identityArguments: '',
        owner: 'ql3_migration',
        securityDefiner: false,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'register_plugin_package_automation_disposition_event',
        identityArguments: '',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'enforce_plugin_package_stage_provenance',
        identityArguments: '',
        owner: 'ql3_migration',
        securityDefiner: false,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'lock_active_plugin_package_project',
        identityArguments: 'character varying',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'lock_approval_policy_fence',
        identityArguments:
          'character varying, character varying, character varying, integer, integer',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'lock_run_management_policy_fence',
        identityArguments:
          'character varying, character varying, character varying, integer, integer',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'commit_plugin_package_task_reconciliation',
        identityArguments:
          'p_generation_digest character, p_materialized_revision_digest character, p_receipt jsonb, p_writes jsonb, p_execution_revisions jsonb',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'plugin_package_run_start_allowed',
        identityArguments:
          'p_project_id character varying, p_task_id character varying, p_task_revision character varying',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'plugin_package_tool_start_allowed',
        identityArguments:
          'p_project_id character varying, p_definition_ref character varying, p_definition_digest character',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'plugin_package_automation_start_allowed',
        identityArguments:
          'p_project_id character varying, p_package_name character varying, p_publication_digest character',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'plugin_package_workflow_admission_snapshot',
        identityArguments:
          'p_project_id character varying, p_package_name character varying, p_publication_digest character',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'plugin_package_workflow_task_attempt_snapshot',
        identityArguments:
          'p_run_id character varying, p_step_run_id character varying',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'commit_plugin_package_quarantine',
        identityArguments:
          'p_event jsonb, p_receipt jsonb, p_task_writes jsonb, p_snapshot jsonb',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'plugin_package_lifecycle_blocking_runs',
        identityArguments:
          'p_project_id character varying, p_package_name character varying, p_limit integer',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
      Object.freeze({
        name: 'commit_plugin_package_lifecycle',
        identityArguments:
          'p_event jsonb, p_receipt jsonb, p_task_writes jsonb, p_snapshot jsonb',
        owner: 'ql3_migration',
        securityDefiner: true,
        volatility: 'volatile',
        configuration: Object.freeze(['search_path=pg_catalog, ql3']),
      }),
    ]),
    triggers: Object.freeze([
      Object.freeze({
        name: 'ql3_plugin_package_secret_binding_target_guard',
        tableName: 'plugin_package_secret_bindings',
        functionName: 'enforce_plugin_package_secret_binding_target',
      }),
      Object.freeze({
        name: 'ql3_package_secret_transition_receipt_target_guard',
        tableName: 'plugin_package_secret_binding_transition_receipts',
        functionName:
          'enforce_plugin_package_secret_binding_transition_receipt_target',
      }),
      Object.freeze({
        name: 'ql3_plugin_package_secret_materialization_guard',
        tableName: 'plugin_package_materialized_revisions',
        functionName: 'enforce_plugin_package_secret_materialization',
      }),
    ]),
  });
