apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ql3-plugin-package-executor
  namespace: qinglong3-system
  labels:
    app.kubernetes.io/name: ql3-plugin-package-executor
    app.kubernetes.io/component: plugin-package-executor
    app.kubernetes.io/part-of: qinglong3
subjects:
  - kind: ServiceAccount
    name: ql3-plugin-package-executor
    namespace: qinglong3-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ql3-plugin-package-executor
