apiVersion: v1
kind: ServiceAccount
metadata:
  name: ql3-approval-management-client
  namespace: qinglong3-system
  labels:
    app.kubernetes.io/name: ql3-approval-management-client
    app.kubernetes.io/component: approval-management-client
    app.kubernetes.io/part-of: qinglong3
automountServiceAccountToken: false
