apiVersion: v1
kind: ServiceAccount
metadata:
  name: ql3-worker-credential-executor
  namespace: qinglong3-system
  labels:
    app.kubernetes.io/name: ql3-worker-credential-executor
    app.kubernetes.io/component: worker-credential-executor
    app.kubernetes.io/part-of: qinglong3
automountServiceAccountToken: false
