apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: qinglong3-cluster-control
    newName: registry.example.com/qinglong/qinglong3-cluster-control
    newTag: 3.0.0-alpha.2
