apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - stage-role.yaml
  - stage-role-binding.yaml
  - target-role.yaml
  - target-role-binding.yaml
  - token-issuer-role.yaml
  - token-issuer-role-binding.yaml
