apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ql3-worker-credential-target-admin
  namespace: qinglong3-worker
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - ql3-worker-credential
    verbs:
      - get
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    resourceNames:
      - ql3-worker
    verbs:
      - get
      - update
