apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ql3-postgres
spec:
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: ql3-postgres-backup
