// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { PluginManager } from 'umi';

function __defaultExport(obj) {
  if (obj.default) {
    return typeof obj.default === 'function' ? obj.default() : obj.default;
  }
  return obj;
}
export function getPlugins() {
  return [];
}

export function getValidKeys() {
  return [
    'patchRoutes',
    'patchClientRoutes',
    'modifyContextOpts',
    'rootContainer',
    'innerProvider',
    'i18nProvider',
    'accessProvider',
    'dataflowProvider',
    'outerProvider',
    'render',
    'onRouteChange',
    'qiankun',
  ];
}

let pluginManager = null;
export function createPluginManager() {
  pluginManager = PluginManager.create({
    plugins: getPlugins(),
    validKeys: getValidKeys(),
  });
  return pluginManager;
}

export function getPluginManager() {
  return pluginManager;
}
