apiVersion: v1
kind: ServiceAccount
metadata:
  name: ql3-security-administration
  namespace: qinglong3-system
  labels:
    app.kubernetes.io/name: ql3-security-administration
    app.kubernetes.io/component: security-administration
    app.kubernetes.io/part-of: qinglong3
automountServiceAccountToken: false
