apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cloudnative-pg

patches:
  - target:
      group: batch
      version: v1
      kind: Job
      labelSelector: app.kubernetes.io/name=ql3-plugin-package-recovery
    path: recover-job-patch.yaml
