- op: replace
  path: /spec/template/spec/containers/0/env
  value:
    - name: QL3_POSTGRES_ADMIN_TLS_MODE
      value: verify-full
    - name: QL3_POSTGRES_ADMIN_TLS_CA_FILE
      value: /var/run/secrets/qinglong3/postgres-security-administration/ca.crt
    - name: QL3_POSTGRES_ADMIN_HOST
      value: ql3-postgres-rw.qinglong3-system.svc
    - name: QL3_POSTGRES_ADMIN_PORT
      value: '5432'
    - name: QL3_POSTGRES_ADMIN_DATABASE
      value: qinglong
    - name: QL3_POSTGRES_ADMIN_USER
      valueFrom:
        secretKeyRef:
          name: ql3-postgres-admin-auth
          key: username
    - name: QL3_POSTGRES_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ql3-postgres-admin-auth
          key: password
    - name: QL3_POSTGRES_ADMIN_TLS_SERVERNAME
      value: ql3-postgres-rw.qinglong3-system.svc
- op: replace
  path: /spec/template/spec/volumes/2/secret/secretName
  value: ql3-postgres-ca
- op: replace
  path: /spec/template/spec/volumes/2/secret/items/0/key
  value: ca.crt
