// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {
      'crontab/viewCreateModal': {
        path: 'crontab/viewCreateModal',
        id: 'crontab/viewCreateModal',
        parentId: '@@/global-layout',
        file: 'crontab/viewCreateModal.tsx',
      },
      'crontab/viewManageModal': {
        path: 'crontab/viewManageModal',
        id: 'crontab/viewManageModal',
        parentId: '@@/global-layout',
        file: 'crontab/viewManageModal.tsx',
      },
      'subscription/logModal': {
        path: 'subscription/logModal',
        id: 'subscription/logModal',
        parentId: '@@/global-layout',
        file: 'subscription/logModal.tsx',
      },
      'initialization/index': {
        path: 'initialization',
        id: 'initialization/index',
        parentId: '@@/global-layout',
        file: 'initialization/index.tsx',
      },
      'script/editNameModal': {
        path: 'script/editNameModal',
        id: 'script/editNameModal',
        parentId: '@@/global-layout',
        file: 'script/editNameModal.tsx',
      },
      'setting/notification': {
        path: 'setting/notification',
        id: 'setting/notification',
        parentId: '@@/global-layout',
        file: 'setting/notification.tsx',
      },
      'dependence/logModal': {
        path: 'dependence/logModal',
        id: 'dependence/logModal',
        parentId: '@@/global-layout',
        file: 'dependence/logModal.tsx',
      },
      'setting/checkUpdate': {
        path: 'setting/checkUpdate',
        id: 'setting/checkUpdate',
        parentId: '@@/global-layout',
        file: 'setting/checkUpdate.tsx',
      },
      'script/renameModal': {
        path: 'script/renameModal',
        id: 'script/renameModal',
        parentId: '@@/global-layout',
        file: 'script/renameModal.tsx',
      },
      'subscription/index': {
        path: 'subscription',
        id: 'subscription/index',
        parentId: '@@/global-layout',
        file: 'subscription/index.tsx',
      },
      'subscription/modal': {
        path: 'subscription/modal',
        id: 'subscription/modal',
        parentId: '@@/global-layout',
        file: 'subscription/modal.tsx',
      },
      'env/editNameModal': {
        path: 'env/editNameModal',
        id: 'env/editNameModal',
        parentId: '@@/global-layout',
        file: 'env/editNameModal.tsx',
      },
      'crontab/logModal': {
        path: 'crontab/logModal',
        id: 'crontab/logModal',
        parentId: '@@/global-layout',
        file: 'crontab/logModal.tsx',
      },
      'dependence/index': {
        path: 'dependence',
        id: 'dependence/index',
        parentId: '@@/global-layout',
        file: 'dependence/index.tsx',
      },
      'dependence/modal': {
        path: 'dependence/modal',
        id: 'dependence/modal',
        parentId: '@@/global-layout',
        file: 'dependence/modal.tsx',
      },
      'script/editModal': {
        path: 'script/editModal',
        id: 'script/editModal',
        parentId: '@@/global-layout',
        file: 'script/editModal.tsx',
      },
      'script/saveModal': {
        path: 'script/saveModal',
        id: 'script/saveModal',
        parentId: '@@/global-layout',
        file: 'script/saveModal.tsx',
      },
      'setting/appModal': {
        path: 'setting/appModal',
        id: 'setting/appModal',
        parentId: '@@/global-layout',
        file: 'setting/appModal.tsx',
      },
      'setting/loginLog': {
        path: 'setting/loginLog',
        id: 'setting/loginLog',
        parentId: '@@/global-layout',
        file: 'setting/loginLog.tsx',
      },
      'setting/security': {
        path: 'setting/security',
        id: 'setting/security',
        parentId: '@@/global-layout',
        file: 'setting/security.tsx',
      },
      'crontab/detail': {
        path: 'crontab/detail',
        id: 'crontab/detail',
        parentId: '@@/global-layout',
        file: 'crontab/detail.tsx',
      },
      'script/setting': {
        path: 'script/setting',
        id: 'script/setting',
        parentId: '@@/global-layout',
        file: 'script/setting.tsx',
      },
      'crontab/index': {
        path: 'crontab',
        id: 'crontab/index',
        parentId: '@@/global-layout',
        file: 'crontab/index.tsx',
      },
      'crontab/modal': {
        path: 'crontab/modal',
        id: 'crontab/modal',
        parentId: '@@/global-layout',
        file: 'crontab/modal.tsx',
      },
      'setting/about': {
        path: 'setting/about',
        id: 'setting/about',
        parentId: '@@/global-layout',
        file: 'setting/about.tsx',
      },
      'setting/index': {
        path: 'setting',
        id: 'setting/index',
        parentId: '@@/global-layout',
        file: 'setting/index.tsx',
      },
      'config/index': {
        path: 'config',
        id: 'config/index',
        parentId: '@@/global-layout',
        file: 'config/index.tsx',
      },
      'script/index': {
        path: 'script',
        id: 'script/index',
        parentId: '@@/global-layout',
        file: 'script/index.tsx',
      },
      'error/index': {
        path: 'error',
        id: 'error/index',
        parentId: '@@/global-layout',
        file: 'error/index.tsx',
      },
      'login/index': {
        path: 'login',
        id: 'login/index',
        parentId: '@@/global-layout',
        file: 'login/index.tsx',
      },
      'diff/index': {
        path: 'diff',
        id: 'diff/index',
        parentId: '@@/global-layout',
        file: 'diff/index.tsx',
      },
      'env/index': {
        path: 'env',
        id: 'env/index',
        parentId: '@@/global-layout',
        file: 'env/index.tsx',
      },
      'env/modal': {
        path: 'env/modal',
        id: 'env/modal',
        parentId: '@@/global-layout',
        file: 'env/modal.tsx',
      },
      'log/index': {
        path: 'log',
        id: 'log/index',
        parentId: '@@/global-layout',
        file: 'log/index.tsx',
      },
      '@@/global-layout': {
        id: '@@/global-layout',
        path: '/',
        file: '@/layouts/index.tsx',
        isLayout: true,
      },
    },
    routeComponents: {
      'crontab/viewCreateModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__crontab__viewCreateModal" */ '../../../src/pages/crontab/viewCreateModal.tsx'
          ),
      ),
      'crontab/viewManageModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__crontab__viewManageModal" */ '../../../src/pages/crontab/viewManageModal.tsx'
          ),
      ),
      'subscription/logModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__subscription__logModal" */ '../../../src/pages/subscription/logModal.tsx'
          ),
      ),
      'initialization/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__initialization__index" */ '../../../src/pages/initialization/index.tsx'
          ),
      ),
      'script/editNameModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__script__editNameModal" */ '../../../src/pages/script/editNameModal.tsx'
          ),
      ),
      'setting/notification': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__setting__notification" */ '../../../src/pages/setting/notification.tsx'
          ),
      ),
      'dependence/logModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__dependence__logModal" */ '../../../src/pages/dependence/logModal.tsx'
          ),
      ),
      'setting/checkUpdate': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__setting__checkUpdate" */ '../../../src/pages/setting/checkUpdate.tsx'
          ),
      ),
      'script/renameModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__script__renameModal" */ '../../../src/pages/script/renameModal.tsx'
          ),
      ),
      'subscription/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__subscription__index" */ '../../../src/pages/subscription/index.tsx'
          ),
      ),
      'subscription/modal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__subscription__modal" */ '../../../src/pages/subscription/modal.tsx'
          ),
      ),
      'env/editNameModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__env__editNameModal" */ '../../../src/pages/env/editNameModal.tsx'
          ),
      ),
      'crontab/logModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__crontab__logModal" */ '../../../src/pages/crontab/logModal.tsx'
          ),
      ),
      'dependence/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__dependence__index" */ '../../../src/pages/dependence/index.tsx'
          ),
      ),
      'dependence/modal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__dependence__modal" */ '../../../src/pages/dependence/modal.tsx'
          ),
      ),
      'script/editModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__script__editModal" */ '../../../src/pages/script/editModal.tsx'
          ),
      ),
      'script/saveModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__script__saveModal" */ '../../../src/pages/script/saveModal.tsx'
          ),
      ),
      'setting/appModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__setting__appModal" */ '../../../src/pages/setting/appModal.tsx'
          ),
      ),
      'setting/loginLog': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__setting__loginLog" */ '../../../src/pages/setting/loginLog.tsx'
          ),
      ),
      'setting/security': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__setting__security" */ '../../../src/pages/setting/security.tsx'
          ),
      ),
      'crontab/detail': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__crontab__detail" */ '../../../src/pages/crontab/detail.tsx'
          ),
      ),
      'script/setting': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__script__setting" */ '../../../src/pages/script/setting.tsx'
          ),
      ),
      'crontab/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__crontab__index" */ '../../../src/pages/crontab/index.tsx'
          ),
      ),
      'crontab/modal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__crontab__modal" */ '../../../src/pages/crontab/modal.tsx'
          ),
      ),
      'setting/about': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__setting__about" */ '../../../src/pages/setting/about.tsx'
          ),
      ),
      'setting/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__setting__index" */ '../../../src/pages/setting/index.tsx'
          ),
      ),
      'config/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__config__index" */ '../../../src/pages/config/index.tsx'
          ),
      ),
      'script/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__script__index" */ '../../../src/pages/script/index.tsx'
          ),
      ),
      'error/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__error__index" */ '../../../src/pages/error/index.tsx'
          ),
      ),
      'login/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__login__index" */ '../../../src/pages/login/index.tsx'
          ),
      ),
      'diff/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__diff__index" */ '../../../src/pages/diff/index.tsx'
          ),
      ),
      'env/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__env__index" */ '../../../src/pages/env/index.tsx'
          ),
      ),
      'env/modal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__env__modal" */ '../../../src/pages/env/modal.tsx'
          ),
      ),
      'log/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "src__pages__log__index" */ '../../../src/pages/log/index.tsx'
          ),
      ),
      '@@/global-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "layouts__index" */ '@/layouts/index.tsx'
          ),
      ),
    },
  };
}
