apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ql3-automation-management
  namespace: qinglong3-system
  labels:
    app.kubernetes.io/name: ql3-automation-management
    app.kubernetes.io/component: automation-management
    app.kubernetes.io/part-of: qinglong3
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ql3-automation-management
      app.kubernetes.io/component: automation-management
